#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SimpleAuth.Resource.Id.loginButton = global::Sample.Droid.Resource.Id.loginButton;
			global::SimpleAuth.Resource.Id.password = global::Sample.Droid.Resource.Id.password;
			global::SimpleAuth.Resource.Id.username = global::Sample.Droid.Resource.Id.username;
			global::SimpleAuth.Resource.Layout.login = global::Sample.Droid.Resource.Layout.login;
			global::SimpleAuth.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::SimpleAuth.Google.Droid.Resource.Attribute.buttonSize = global::Sample.Droid.Resource.Attribute.buttonSize;
			global::SimpleAuth.Google.Droid.Resource.Attribute.circleCrop = global::Sample.Droid.Resource.Attribute.circleCrop;
			global::SimpleAuth.Google.Droid.Resource.Attribute.colorScheme = global::Sample.Droid.Resource.Attribute.colorScheme;
			global::SimpleAuth.Google.Droid.Resource.Attribute.font = global::Sample.Droid.Resource.Attribute.font;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderAuthority = global::Sample.Droid.Resource.Attribute.fontProviderAuthority;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderCerts = global::Sample.Droid.Resource.Attribute.fontProviderCerts;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderFetchStrategy = global::Sample.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderFetchTimeout = global::Sample.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderPackage = global::Sample.Droid.Resource.Attribute.fontProviderPackage;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderQuery = global::Sample.Droid.Resource.Attribute.fontProviderQuery;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontStyle = global::Sample.Droid.Resource.Attribute.fontStyle;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontWeight = global::Sample.Droid.Resource.Attribute.fontWeight;
			global::SimpleAuth.Google.Droid.Resource.Attribute.imageAspectRatio = global::Sample.Droid.Resource.Attribute.imageAspectRatio;
			global::SimpleAuth.Google.Droid.Resource.Attribute.imageAspectRatioAdjust = global::Sample.Droid.Resource.Attribute.imageAspectRatioAdjust;
			global::SimpleAuth.Google.Droid.Resource.Attribute.scopeUris = global::Sample.Droid.Resource.Attribute.scopeUris;
			global::SimpleAuth.Google.Droid.Resource.Boolean.abc_action_bar_embed_tabs = global::Sample.Droid.Resource.Boolean.abc_action_bar_embed_tabs;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_default = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_default = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_disabled = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_focused = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_pressed = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_tint = global::Sample.Droid.Resource.Color.common_google_signin_btn_tint;
			global::SimpleAuth.Google.Droid.Resource.Color.notification_action_color_filter = global::Sample.Droid.Resource.Color.notification_action_color_filter;
			global::SimpleAuth.Google.Droid.Resource.Color.notification_icon_bg_color = global::Sample.Droid.Resource.Color.notification_icon_bg_color;
			global::SimpleAuth.Google.Droid.Resource.Color.notification_material_background_media_default_color = global::Sample.Droid.Resource.Color.notification_material_background_media_default_color;
			global::SimpleAuth.Google.Droid.Resource.Color.primary_text_default_material_dark = global::Sample.Droid.Resource.Color.primary_text_default_material_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.ripple_material_light = global::Sample.Droid.Resource.Color.ripple_material_light;
			global::SimpleAuth.Google.Droid.Resource.Color.secondary_text_default_material_dark = global::Sample.Droid.Resource.Color.secondary_text_default_material_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.secondary_text_default_material_light = global::Sample.Droid.Resource.Color.secondary_text_default_material_light;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_inset_horizontal_material = global::Sample.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_inset_vertical_material = global::Sample.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_padding_horizontal_material = global::Sample.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_padding_vertical_material = global::Sample.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_control_corner_material = global::Sample.Droid.Resource.Dimension.compat_control_corner_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_action_icon_size = global::Sample.Droid.Resource.Dimension.notification_action_icon_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_action_text_size = global::Sample.Droid.Resource.Dimension.notification_action_text_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_big_circle_margin = global::Sample.Droid.Resource.Dimension.notification_big_circle_margin;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_content_margin_start = global::Sample.Droid.Resource.Dimension.notification_content_margin_start;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_large_icon_height = global::Sample.Droid.Resource.Dimension.notification_large_icon_height;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_large_icon_width = global::Sample.Droid.Resource.Dimension.notification_large_icon_width;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_main_column_padding_top = global::Sample.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_media_narrow_margin = global::Sample.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_right_icon_size = global::Sample.Droid.Resource.Dimension.notification_right_icon_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_right_side_padding_top = global::Sample.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_small_icon_background_padding = global::Sample.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_small_icon_size_as_large = global::Sample.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_subtext_size = global::Sample.Droid.Resource.Dimension.notification_subtext_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_top_pad = global::Sample.Droid.Resource.Dimension.notification_top_pad;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_top_pad_large_text = global::Sample.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_full_open_on_phone = global::Sample.Droid.Resource.Drawable.common_full_open_on_phone;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.googleg_disabled_color_18 = global::Sample.Droid.Resource.Drawable.googleg_disabled_color_18;
			global::SimpleAuth.Google.Droid.Resource.Drawable.googleg_standard_color_18 = global::Sample.Droid.Resource.Drawable.googleg_standard_color_18;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_action_background = global::Sample.Droid.Resource.Drawable.notification_action_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg = global::Sample.Droid.Resource.Drawable.notification_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_low = global::Sample.Droid.Resource.Drawable.notification_bg_low;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_low_normal = global::Sample.Droid.Resource.Drawable.notification_bg_low_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_low_pressed = global::Sample.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_normal = global::Sample.Droid.Resource.Drawable.notification_bg_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_normal_pressed = global::Sample.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_icon_background = global::Sample.Droid.Resource.Drawable.notification_icon_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_template_icon_bg = global::Sample.Droid.Resource.Drawable.notification_template_icon_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_template_icon_low_bg = global::Sample.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_tile_bg = global::Sample.Droid.Resource.Drawable.notification_tile_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notify_panel_notification_icon_bg = global::Sample.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::SimpleAuth.Google.Droid.Resource.Id.action0 = global::Sample.Droid.Resource.Id.action0;
			global::SimpleAuth.Google.Droid.Resource.Id.action_container = global::Sample.Droid.Resource.Id.action_container;
			global::SimpleAuth.Google.Droid.Resource.Id.action_divider = global::Sample.Droid.Resource.Id.action_divider;
			global::SimpleAuth.Google.Droid.Resource.Id.action_image = global::Sample.Droid.Resource.Id.action_image;
			global::SimpleAuth.Google.Droid.Resource.Id.action_text = global::Sample.Droid.Resource.Id.action_text;
			global::SimpleAuth.Google.Droid.Resource.Id.actions = global::Sample.Droid.Resource.Id.actions;
			global::SimpleAuth.Google.Droid.Resource.Id.adjust_height = global::Sample.Droid.Resource.Id.adjust_height;
			global::SimpleAuth.Google.Droid.Resource.Id.adjust_width = global::Sample.Droid.Resource.Id.adjust_width;
			global::SimpleAuth.Google.Droid.Resource.Id.async = global::Sample.Droid.Resource.Id.async;
			global::SimpleAuth.Google.Droid.Resource.Id.auto = global::Sample.Droid.Resource.Id.auto;
			global::SimpleAuth.Google.Droid.Resource.Id.blocking = global::Sample.Droid.Resource.Id.blocking;
			global::SimpleAuth.Google.Droid.Resource.Id.cancel_action = global::Sample.Droid.Resource.Id.cancel_action;
			global::SimpleAuth.Google.Droid.Resource.Id.chronometer = global::Sample.Droid.Resource.Id.chronometer;
			global::SimpleAuth.Google.Droid.Resource.Id.dark = global::Sample.Droid.Resource.Id.dark;
			global::SimpleAuth.Google.Droid.Resource.Id.end_padder = global::Sample.Droid.Resource.Id.end_padder;
			global::SimpleAuth.Google.Droid.Resource.Id.forever = global::Sample.Droid.Resource.Id.forever;
			global::SimpleAuth.Google.Droid.Resource.Id.icon = global::Sample.Droid.Resource.Id.icon;
			global::SimpleAuth.Google.Droid.Resource.Id.icon_group = global::Sample.Droid.Resource.Id.icon_group;
			global::SimpleAuth.Google.Droid.Resource.Id.icon_only = global::Sample.Droid.Resource.Id.icon_only;
			global::SimpleAuth.Google.Droid.Resource.Id.info = global::Sample.Droid.Resource.Id.info;
			global::SimpleAuth.Google.Droid.Resource.Id.italic = global::Sample.Droid.Resource.Id.italic;
			global::SimpleAuth.Google.Droid.Resource.Id.light = global::Sample.Droid.Resource.Id.light;
			global::SimpleAuth.Google.Droid.Resource.Id.line1 = global::Sample.Droid.Resource.Id.line1;
			global::SimpleAuth.Google.Droid.Resource.Id.line3 = global::Sample.Droid.Resource.Id.line3;
			global::SimpleAuth.Google.Droid.Resource.Id.loginButton = global::Sample.Droid.Resource.Id.loginButton;
			global::SimpleAuth.Google.Droid.Resource.Id.media_actions = global::Sample.Droid.Resource.Id.media_actions;
			global::SimpleAuth.Google.Droid.Resource.Id.none = global::Sample.Droid.Resource.Id.none;
			global::SimpleAuth.Google.Droid.Resource.Id.normal = global::Sample.Droid.Resource.Id.normal;
			global::SimpleAuth.Google.Droid.Resource.Id.notification_background = global::Sample.Droid.Resource.Id.notification_background;
			global::SimpleAuth.Google.Droid.Resource.Id.notification_main_column = global::Sample.Droid.Resource.Id.notification_main_column;
			global::SimpleAuth.Google.Droid.Resource.Id.notification_main_column_container = global::Sample.Droid.Resource.Id.notification_main_column_container;
			global::SimpleAuth.Google.Droid.Resource.Id.password = global::Sample.Droid.Resource.Id.password;
			global::SimpleAuth.Google.Droid.Resource.Id.right_icon = global::Sample.Droid.Resource.Id.right_icon;
			global::SimpleAuth.Google.Droid.Resource.Id.right_side = global::Sample.Droid.Resource.Id.right_side;
			global::SimpleAuth.Google.Droid.Resource.Id.standard = global::Sample.Droid.Resource.Id.standard;
			global::SimpleAuth.Google.Droid.Resource.Id.status_bar_latest_event_content = global::Sample.Droid.Resource.Id.status_bar_latest_event_content;
			global::SimpleAuth.Google.Droid.Resource.Id.text = global::Sample.Droid.Resource.Id.text;
			global::SimpleAuth.Google.Droid.Resource.Id.text2 = global::Sample.Droid.Resource.Id.text2;
			global::SimpleAuth.Google.Droid.Resource.Id.time = global::Sample.Droid.Resource.Id.time;
			global::SimpleAuth.Google.Droid.Resource.Id.title = global::Sample.Droid.Resource.Id.title;
			global::SimpleAuth.Google.Droid.Resource.Id.username = global::Sample.Droid.Resource.Id.username;
			global::SimpleAuth.Google.Droid.Resource.Id.wide = global::Sample.Droid.Resource.Id.wide;
			global::SimpleAuth.Google.Droid.Resource.Integer.cancel_button_image_alpha = global::Sample.Droid.Resource.Integer.cancel_button_image_alpha;
			global::SimpleAuth.Google.Droid.Resource.Integer.google_play_services_version = global::Sample.Droid.Resource.Integer.google_play_services_version;
			global::SimpleAuth.Google.Droid.Resource.Integer.status_bar_notification_info_maxnum = global::Sample.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::SimpleAuth.Google.Droid.Resource.Layout.login = global::Sample.Droid.Resource.Layout.login;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_action = global::Sample.Droid.Resource.Layout.notification_action;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_action_tombstone = global::Sample.Droid.Resource.Layout.notification_action_tombstone;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_media_action = global::Sample.Droid.Resource.Layout.notification_media_action;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_media_cancel_action = global::Sample.Droid.Resource.Layout.notification_media_cancel_action;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media = global::Sample.Droid.Resource.Layout.notification_template_big_media;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media_custom = global::Sample.Droid.Resource.Layout.notification_template_big_media_custom;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media_narrow = global::Sample.Droid.Resource.Layout.notification_template_big_media_narrow;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media_narrow_custom = global::Sample.Droid.Resource.Layout.notification_template_big_media_narrow_custom;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_custom_big = global::Sample.Droid.Resource.Layout.notification_template_custom_big;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_icon_group = global::Sample.Droid.Resource.Layout.notification_template_icon_group;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_lines_media = global::Sample.Droid.Resource.Layout.notification_template_lines_media;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_media = global::Sample.Droid.Resource.Layout.notification_template_media;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_media_custom = global::Sample.Droid.Resource.Layout.notification_template_media_custom;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_part_chronometer = global::Sample.Droid.Resource.Layout.notification_template_part_chronometer;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_part_time = global::Sample.Droid.Resource.Layout.notification_template_part_time;
			global::SimpleAuth.Google.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Google.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_button = global::Sample.Droid.Resource.String.common_google_play_services_enable_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_text = global::Sample.Droid.Resource.String.common_google_play_services_enable_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_title = global::Sample.Droid.Resource.String.common_google_play_services_enable_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_button = global::Sample.Droid.Resource.String.common_google_play_services_install_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_text = global::Sample.Droid.Resource.String.common_google_play_services_install_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_title = global::Sample.Droid.Resource.String.common_google_play_services_install_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_notification_ticker = global::Sample.Droid.Resource.String.common_google_play_services_notification_ticker;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_unknown_issue = global::Sample.Droid.Resource.String.common_google_play_services_unknown_issue;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_unsupported_text = global::Sample.Droid.Resource.String.common_google_play_services_unsupported_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_button = global::Sample.Droid.Resource.String.common_google_play_services_update_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_text = global::Sample.Droid.Resource.String.common_google_play_services_update_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_title = global::Sample.Droid.Resource.String.common_google_play_services_update_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_updating_text = global::Sample.Droid.Resource.String.common_google_play_services_updating_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_wear_update_text = global::Sample.Droid.Resource.String.common_google_play_services_wear_update_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_open_on_phone = global::Sample.Droid.Resource.String.common_open_on_phone;
			global::SimpleAuth.Google.Droid.Resource.String.common_signin_button_text = global::Sample.Droid.Resource.String.common_signin_button_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_signin_button_text_long = global::Sample.Droid.Resource.String.common_signin_button_text_long;
			global::SimpleAuth.Google.Droid.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::SimpleAuth.Google.Droid.Resource.String.status_bar_notification_info_overflow = global::Sample.Droid.Resource.String.status_bar_notification_info_overflow;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Info = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Time = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Title = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.Widget_Compat_NotificationActionContainer = global::Sample.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::SimpleAuth.Google.Droid.Resource.Style.Widget_Compat_NotificationActionText = global::Sample.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily = global::Sample.Droid.Resource.Styleable.FontFamily;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderAuthority = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderCerts = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderPackage = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderQuery = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont = global::Sample.Droid.Resource.Styleable.FontFamilyFont;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_font = global::Sample.Droid.Resource.Styleable.FontFamilyFont_font;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_fontStyle = global::Sample.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_fontWeight = global::Sample.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView = global::Sample.Droid.Resource.Styleable.LoadingImageView;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_circleCrop = global::Sample.Droid.Resource.Styleable.LoadingImageView_circleCrop;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton = global::Sample.Droid.Resource.Styleable.SignInButton;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_buttonSize = global::Sample.Droid.Resource.Styleable.SignInButton_buttonSize;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_colorScheme = global::Sample.Droid.Resource.Styleable.SignInButton_colorScheme;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_scopeUris = global::Sample.Droid.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public const int font = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderAuthority = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int fontProviderCerts = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderFetchStrategy = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderFetchTimeout = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int fontProviderPackage = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fontProviderQuery = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int fontStyle = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int fontWeight = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_dark = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_tint = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int notification_action_color_filter = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int notification_icon_bg_color = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int notification_material_background_media_default_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int primary_text_default_material_dark = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int ripple_material_light = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int secondary_text_default_material_dark = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int secondary_text_default_material_light = 2131099662;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public const int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notification_action_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int notification_bg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_bg_low = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg_low_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_low_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_normal_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_icon_background = 2130837533;
			
			// aapt resource value: 0x7f020020
			public const int notification_template_icon_bg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_template_icon_low_bg = 2130837537;
			
			// aapt resource value: 0x7f02001e
			public const int notification_tile_bg = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notify_panel_notification_icon_bg = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001d
			public const int action0 = 2131361821;
			
			// aapt resource value: 0x7f0a001a
			public const int action_container = 2131361818;
			
			// aapt resource value: 0x7f0a0021
			public const int action_divider = 2131361825;
			
			// aapt resource value: 0x7f0a001b
			public const int action_image = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int action_text = 2131361820;
			
			// aapt resource value: 0x7f0a002b
			public const int actions = 2131361835;
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000e
			public const int async = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public const int auto = 2131361803;
			
			// aapt resource value: 0x7f0a000f
			public const int blocking = 2131361807;
			
			// aapt resource value: 0x7f0a001e
			public const int cancel_action = 2131361822;
			
			// aapt resource value: 0x7f0a0026
			public const int chronometer = 2131361830;
			
			// aapt resource value: 0x7f0a000c
			public const int dark = 2131361804;
			
			// aapt resource value: 0x7f0a002d
			public const int end_padder = 2131361837;
			
			// aapt resource value: 0x7f0a0010
			public const int forever = 2131361808;
			
			// aapt resource value: 0x7f0a0028
			public const int icon = 2131361832;
			
			// aapt resource value: 0x7f0a002c
			public const int icon_group = 2131361836;
			
			// aapt resource value: 0x7f0a0008
			public const int icon_only = 2131361800;
			
			// aapt resource value: 0x7f0a0027
			public const int info = 2131361831;
			
			// aapt resource value: 0x7f0a0011
			public const int italic = 2131361809;
			
			// aapt resource value: 0x7f0a000d
			public const int light = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0015
			public const int loginButton = 2131361813;
			
			// aapt resource value: 0x7f0a0019
			public const int loginFacebookNative = 2131361817;
			
			// aapt resource value: 0x7f0a0017
			public const int loginGeneric = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int loginGoogleNative = 2131361816;
			
			// aapt resource value: 0x7f0a0020
			public const int media_actions = 2131361824;
			
			// aapt resource value: 0x7f0a0007
			public const int none = 2131361799;
			
			// aapt resource value: 0x7f0a0012
			public const int normal = 2131361810;
			
			// aapt resource value: 0x7f0a002a
			public const int notification_background = 2131361834;
			
			// aapt resource value: 0x7f0a0023
			public const int notification_main_column = 2131361827;
			
			// aapt resource value: 0x7f0a0022
			public const int notification_main_column_container = 2131361826;
			
			// aapt resource value: 0x7f0a0014
			public const int password = 2131361812;
			
			// aapt resource value: 0x7f0a0029
			public const int right_icon = 2131361833;
			
			// aapt resource value: 0x7f0a0024
			public const int right_side = 2131361828;
			
			// aapt resource value: 0x7f0a0009
			public const int standard = 2131361801;
			
			// aapt resource value: 0x7f0a001f
			public const int status_bar_latest_event_content = 2131361823;
			
			// aapt resource value: 0x7f0a0002
			public const int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a0016
			public const int textView1 = 2131361814;
			
			// aapt resource value: 0x7f0a0025
			public const int time = 2131361829;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			// aapt resource value: 0x7f0a0013
			public const int username = 2131361811;
			
			// aapt resource value: 0x7f0a000a
			public const int wide = 2131361802;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040001
			public const int cancel_button_image_alpha = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int status_bar_notification_info_maxnum = 2130968578;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action_tombstone = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_media_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_media_cancel_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_narrow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_big_media_narrow_custom = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_custom_big = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_icon_group = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_lines_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_media_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_part_chronometer = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_part_time = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050014
			public const int ApplicationName = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int Hello = 2131034131;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int facebook_app_id = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int fb_login_protocol_scheme = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int library_name = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int status_bar_notification_info_overflow = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public const int TextAppearance_Compat_Notification = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int TextAppearance_Compat_Notification_Info = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int TextAppearance_Compat_Notification_Media = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Time = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int TextAppearance_Compat_Notification_Title = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int Widget_Compat_NotificationActionContainer = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int Widget_Compat_NotificationActionText = 2131165194;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
