#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SimpleAuth.Resource.Id.loginButton = global::Sample.Droid.Resource.Id.loginButton;
			global::SimpleAuth.Resource.Id.password = global::Sample.Droid.Resource.Id.password;
			global::SimpleAuth.Resource.Id.username = global::Sample.Droid.Resource.Id.username;
			global::SimpleAuth.Resource.Layout.login = global::Sample.Droid.Resource.Layout.login;
			global::SimpleAuth.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::SimpleAuth.Google.Droid.Resource.Attribute.alpha = global::Sample.Droid.Resource.Attribute.alpha;
			global::SimpleAuth.Google.Droid.Resource.Attribute.buttonSize = global::Sample.Droid.Resource.Attribute.buttonSize;
			global::SimpleAuth.Google.Droid.Resource.Attribute.circleCrop = global::Sample.Droid.Resource.Attribute.circleCrop;
			global::SimpleAuth.Google.Droid.Resource.Attribute.colorScheme = global::Sample.Droid.Resource.Attribute.colorScheme;
			global::SimpleAuth.Google.Droid.Resource.Attribute.coordinatorLayoutStyle = global::Sample.Droid.Resource.Attribute.coordinatorLayoutStyle;
			global::SimpleAuth.Google.Droid.Resource.Attribute.font = global::Sample.Droid.Resource.Attribute.font;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderAuthority = global::Sample.Droid.Resource.Attribute.fontProviderAuthority;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderCerts = global::Sample.Droid.Resource.Attribute.fontProviderCerts;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderFetchStrategy = global::Sample.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderFetchTimeout = global::Sample.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderPackage = global::Sample.Droid.Resource.Attribute.fontProviderPackage;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontProviderQuery = global::Sample.Droid.Resource.Attribute.fontProviderQuery;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontStyle = global::Sample.Droid.Resource.Attribute.fontStyle;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontVariationSettings = global::Sample.Droid.Resource.Attribute.fontVariationSettings;
			global::SimpleAuth.Google.Droid.Resource.Attribute.fontWeight = global::Sample.Droid.Resource.Attribute.fontWeight;
			global::SimpleAuth.Google.Droid.Resource.Attribute.imageAspectRatio = global::Sample.Droid.Resource.Attribute.imageAspectRatio;
			global::SimpleAuth.Google.Droid.Resource.Attribute.imageAspectRatioAdjust = global::Sample.Droid.Resource.Attribute.imageAspectRatioAdjust;
			global::SimpleAuth.Google.Droid.Resource.Attribute.keylines = global::Sample.Droid.Resource.Attribute.keylines;
			global::SimpleAuth.Google.Droid.Resource.Attribute.layout_anchor = global::Sample.Droid.Resource.Attribute.layout_anchor;
			global::SimpleAuth.Google.Droid.Resource.Attribute.layout_anchorGravity = global::Sample.Droid.Resource.Attribute.layout_anchorGravity;
			global::SimpleAuth.Google.Droid.Resource.Attribute.layout_behavior = global::Sample.Droid.Resource.Attribute.layout_behavior;
			global::SimpleAuth.Google.Droid.Resource.Attribute.layout_dodgeInsetEdges = global::Sample.Droid.Resource.Attribute.layout_dodgeInsetEdges;
			global::SimpleAuth.Google.Droid.Resource.Attribute.layout_insetEdge = global::Sample.Droid.Resource.Attribute.layout_insetEdge;
			global::SimpleAuth.Google.Droid.Resource.Attribute.layout_keyline = global::Sample.Droid.Resource.Attribute.layout_keyline;
			global::SimpleAuth.Google.Droid.Resource.Attribute.scopeUris = global::Sample.Droid.Resource.Attribute.scopeUris;
			global::SimpleAuth.Google.Droid.Resource.Attribute.statusBarBackground = global::Sample.Droid.Resource.Attribute.statusBarBackground;
			global::SimpleAuth.Google.Droid.Resource.Attribute.ttcIndex = global::Sample.Droid.Resource.Attribute.ttcIndex;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_default = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_default = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_disabled = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_focused = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_pressed = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_tint = global::Sample.Droid.Resource.Color.common_google_signin_btn_tint;
			global::SimpleAuth.Google.Droid.Resource.Color.notification_action_color_filter = global::Sample.Droid.Resource.Color.notification_action_color_filter;
			global::SimpleAuth.Google.Droid.Resource.Color.notification_icon_bg_color = global::Sample.Droid.Resource.Color.notification_icon_bg_color;
			global::SimpleAuth.Google.Droid.Resource.Color.notification_material_background_media_default_color = global::Sample.Droid.Resource.Color.notification_material_background_media_default_color;
			global::SimpleAuth.Google.Droid.Resource.Color.primary_text_default_material_dark = global::Sample.Droid.Resource.Color.primary_text_default_material_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.ripple_material_light = global::Sample.Droid.Resource.Color.ripple_material_light;
			global::SimpleAuth.Google.Droid.Resource.Color.secondary_text_default_material_dark = global::Sample.Droid.Resource.Color.secondary_text_default_material_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.secondary_text_default_material_light = global::Sample.Droid.Resource.Color.secondary_text_default_material_light;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_inset_horizontal_material = global::Sample.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_inset_vertical_material = global::Sample.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_padding_horizontal_material = global::Sample.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_button_padding_vertical_material = global::Sample.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_control_corner_material = global::Sample.Droid.Resource.Dimension.compat_control_corner_material;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_notification_large_icon_max_height = global::Sample.Droid.Resource.Dimension.compat_notification_large_icon_max_height;
			global::SimpleAuth.Google.Droid.Resource.Dimension.compat_notification_large_icon_max_width = global::Sample.Droid.Resource.Dimension.compat_notification_large_icon_max_width;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_action_icon_size = global::Sample.Droid.Resource.Dimension.notification_action_icon_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_action_text_size = global::Sample.Droid.Resource.Dimension.notification_action_text_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_big_circle_margin = global::Sample.Droid.Resource.Dimension.notification_big_circle_margin;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_content_margin_start = global::Sample.Droid.Resource.Dimension.notification_content_margin_start;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_large_icon_height = global::Sample.Droid.Resource.Dimension.notification_large_icon_height;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_large_icon_width = global::Sample.Droid.Resource.Dimension.notification_large_icon_width;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_main_column_padding_top = global::Sample.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_media_narrow_margin = global::Sample.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_right_icon_size = global::Sample.Droid.Resource.Dimension.notification_right_icon_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_right_side_padding_top = global::Sample.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_small_icon_background_padding = global::Sample.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_small_icon_size_as_large = global::Sample.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_subtext_size = global::Sample.Droid.Resource.Dimension.notification_subtext_size;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_top_pad = global::Sample.Droid.Resource.Dimension.notification_top_pad;
			global::SimpleAuth.Google.Droid.Resource.Dimension.notification_top_pad_large_text = global::Sample.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::SimpleAuth.Google.Droid.Resource.Dimension.subtitle_corner_radius = global::Sample.Droid.Resource.Dimension.subtitle_corner_radius;
			global::SimpleAuth.Google.Droid.Resource.Dimension.subtitle_outline_width = global::Sample.Droid.Resource.Dimension.subtitle_outline_width;
			global::SimpleAuth.Google.Droid.Resource.Dimension.subtitle_shadow_offset = global::Sample.Droid.Resource.Dimension.subtitle_shadow_offset;
			global::SimpleAuth.Google.Droid.Resource.Dimension.subtitle_shadow_radius = global::Sample.Droid.Resource.Dimension.subtitle_shadow_radius;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_full_open_on_phone = global::Sample.Droid.Resource.Drawable.common_full_open_on_phone;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal_background = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.googleg_disabled_color_18 = global::Sample.Droid.Resource.Drawable.googleg_disabled_color_18;
			global::SimpleAuth.Google.Droid.Resource.Drawable.googleg_standard_color_18 = global::Sample.Droid.Resource.Drawable.googleg_standard_color_18;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_action_background = global::Sample.Droid.Resource.Drawable.notification_action_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg = global::Sample.Droid.Resource.Drawable.notification_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_low = global::Sample.Droid.Resource.Drawable.notification_bg_low;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_low_normal = global::Sample.Droid.Resource.Drawable.notification_bg_low_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_low_pressed = global::Sample.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_normal = global::Sample.Droid.Resource.Drawable.notification_bg_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_bg_normal_pressed = global::Sample.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_icon_background = global::Sample.Droid.Resource.Drawable.notification_icon_background;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_template_icon_bg = global::Sample.Droid.Resource.Drawable.notification_template_icon_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_template_icon_low_bg = global::Sample.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notification_tile_bg = global::Sample.Droid.Resource.Drawable.notification_tile_bg;
			global::SimpleAuth.Google.Droid.Resource.Drawable.notify_panel_notification_icon_bg = global::Sample.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::SimpleAuth.Google.Droid.Resource.Id.action0 = global::Sample.Droid.Resource.Id.action0;
			global::SimpleAuth.Google.Droid.Resource.Id.actions = global::Sample.Droid.Resource.Id.actions;
			global::SimpleAuth.Google.Droid.Resource.Id.action_container = global::Sample.Droid.Resource.Id.action_container;
			global::SimpleAuth.Google.Droid.Resource.Id.action_divider = global::Sample.Droid.Resource.Id.action_divider;
			global::SimpleAuth.Google.Droid.Resource.Id.action_image = global::Sample.Droid.Resource.Id.action_image;
			global::SimpleAuth.Google.Droid.Resource.Id.action_text = global::Sample.Droid.Resource.Id.action_text;
			global::SimpleAuth.Google.Droid.Resource.Id.adjust_height = global::Sample.Droid.Resource.Id.adjust_height;
			global::SimpleAuth.Google.Droid.Resource.Id.adjust_width = global::Sample.Droid.Resource.Id.adjust_width;
			global::SimpleAuth.Google.Droid.Resource.Id.all = global::Sample.Droid.Resource.Id.all;
			global::SimpleAuth.Google.Droid.Resource.Id.async = global::Sample.Droid.Resource.Id.async;
			global::SimpleAuth.Google.Droid.Resource.Id.auto = global::Sample.Droid.Resource.Id.auto;
			global::SimpleAuth.Google.Droid.Resource.Id.blocking = global::Sample.Droid.Resource.Id.blocking;
			global::SimpleAuth.Google.Droid.Resource.Id.bottom = global::Sample.Droid.Resource.Id.bottom;
			global::SimpleAuth.Google.Droid.Resource.Id.cancel_action = global::Sample.Droid.Resource.Id.cancel_action;
			global::SimpleAuth.Google.Droid.Resource.Id.center = global::Sample.Droid.Resource.Id.center;
			global::SimpleAuth.Google.Droid.Resource.Id.center_horizontal = global::Sample.Droid.Resource.Id.center_horizontal;
			global::SimpleAuth.Google.Droid.Resource.Id.center_vertical = global::Sample.Droid.Resource.Id.center_vertical;
			global::SimpleAuth.Google.Droid.Resource.Id.chronometer = global::Sample.Droid.Resource.Id.chronometer;
			global::SimpleAuth.Google.Droid.Resource.Id.clip_horizontal = global::Sample.Droid.Resource.Id.clip_horizontal;
			global::SimpleAuth.Google.Droid.Resource.Id.clip_vertical = global::Sample.Droid.Resource.Id.clip_vertical;
			global::SimpleAuth.Google.Droid.Resource.Id.dark = global::Sample.Droid.Resource.Id.dark;
			global::SimpleAuth.Google.Droid.Resource.Id.end = global::Sample.Droid.Resource.Id.end;
			global::SimpleAuth.Google.Droid.Resource.Id.end_padder = global::Sample.Droid.Resource.Id.end_padder;
			global::SimpleAuth.Google.Droid.Resource.Id.fill = global::Sample.Droid.Resource.Id.fill;
			global::SimpleAuth.Google.Droid.Resource.Id.fill_horizontal = global::Sample.Droid.Resource.Id.fill_horizontal;
			global::SimpleAuth.Google.Droid.Resource.Id.fill_vertical = global::Sample.Droid.Resource.Id.fill_vertical;
			global::SimpleAuth.Google.Droid.Resource.Id.forever = global::Sample.Droid.Resource.Id.forever;
			global::SimpleAuth.Google.Droid.Resource.Id.icon = global::Sample.Droid.Resource.Id.icon;
			global::SimpleAuth.Google.Droid.Resource.Id.icon_group = global::Sample.Droid.Resource.Id.icon_group;
			global::SimpleAuth.Google.Droid.Resource.Id.icon_only = global::Sample.Droid.Resource.Id.icon_only;
			global::SimpleAuth.Google.Droid.Resource.Id.info = global::Sample.Droid.Resource.Id.info;
			global::SimpleAuth.Google.Droid.Resource.Id.italic = global::Sample.Droid.Resource.Id.italic;
			global::SimpleAuth.Google.Droid.Resource.Id.left = global::Sample.Droid.Resource.Id.left;
			global::SimpleAuth.Google.Droid.Resource.Id.light = global::Sample.Droid.Resource.Id.light;
			global::SimpleAuth.Google.Droid.Resource.Id.line1 = global::Sample.Droid.Resource.Id.line1;
			global::SimpleAuth.Google.Droid.Resource.Id.line3 = global::Sample.Droid.Resource.Id.line3;
			global::SimpleAuth.Google.Droid.Resource.Id.loginButton = global::Sample.Droid.Resource.Id.loginButton;
			global::SimpleAuth.Google.Droid.Resource.Id.media_actions = global::Sample.Droid.Resource.Id.media_actions;
			global::SimpleAuth.Google.Droid.Resource.Id.none = global::Sample.Droid.Resource.Id.none;
			global::SimpleAuth.Google.Droid.Resource.Id.normal = global::Sample.Droid.Resource.Id.normal;
			global::SimpleAuth.Google.Droid.Resource.Id.notification_background = global::Sample.Droid.Resource.Id.notification_background;
			global::SimpleAuth.Google.Droid.Resource.Id.notification_main_column = global::Sample.Droid.Resource.Id.notification_main_column;
			global::SimpleAuth.Google.Droid.Resource.Id.notification_main_column_container = global::Sample.Droid.Resource.Id.notification_main_column_container;
			global::SimpleAuth.Google.Droid.Resource.Id.password = global::Sample.Droid.Resource.Id.password;
			global::SimpleAuth.Google.Droid.Resource.Id.right = global::Sample.Droid.Resource.Id.right;
			global::SimpleAuth.Google.Droid.Resource.Id.right_icon = global::Sample.Droid.Resource.Id.right_icon;
			global::SimpleAuth.Google.Droid.Resource.Id.right_side = global::Sample.Droid.Resource.Id.right_side;
			global::SimpleAuth.Google.Droid.Resource.Id.standard = global::Sample.Droid.Resource.Id.standard;
			global::SimpleAuth.Google.Droid.Resource.Id.start = global::Sample.Droid.Resource.Id.start;
			global::SimpleAuth.Google.Droid.Resource.Id.status_bar_latest_event_content = global::Sample.Droid.Resource.Id.status_bar_latest_event_content;
			global::SimpleAuth.Google.Droid.Resource.Id.tag_transition_group = global::Sample.Droid.Resource.Id.tag_transition_group;
			global::SimpleAuth.Google.Droid.Resource.Id.tag_unhandled_key_event_manager = global::Sample.Droid.Resource.Id.tag_unhandled_key_event_manager;
			global::SimpleAuth.Google.Droid.Resource.Id.tag_unhandled_key_listeners = global::Sample.Droid.Resource.Id.tag_unhandled_key_listeners;
			global::SimpleAuth.Google.Droid.Resource.Id.text = global::Sample.Droid.Resource.Id.text;
			global::SimpleAuth.Google.Droid.Resource.Id.text2 = global::Sample.Droid.Resource.Id.text2;
			global::SimpleAuth.Google.Droid.Resource.Id.time = global::Sample.Droid.Resource.Id.time;
			global::SimpleAuth.Google.Droid.Resource.Id.title = global::Sample.Droid.Resource.Id.title;
			global::SimpleAuth.Google.Droid.Resource.Id.top = global::Sample.Droid.Resource.Id.top;
			global::SimpleAuth.Google.Droid.Resource.Id.username = global::Sample.Droid.Resource.Id.username;
			global::SimpleAuth.Google.Droid.Resource.Id.wide = global::Sample.Droid.Resource.Id.wide;
			global::SimpleAuth.Google.Droid.Resource.Integer.cancel_button_image_alpha = global::Sample.Droid.Resource.Integer.cancel_button_image_alpha;
			global::SimpleAuth.Google.Droid.Resource.Integer.google_play_services_version = global::Sample.Droid.Resource.Integer.google_play_services_version;
			global::SimpleAuth.Google.Droid.Resource.Integer.status_bar_notification_info_maxnum = global::Sample.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::SimpleAuth.Google.Droid.Resource.Layout.login = global::Sample.Droid.Resource.Layout.login;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_action = global::Sample.Droid.Resource.Layout.notification_action;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_action_tombstone = global::Sample.Droid.Resource.Layout.notification_action_tombstone;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_media_action = global::Sample.Droid.Resource.Layout.notification_media_action;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_media_cancel_action = global::Sample.Droid.Resource.Layout.notification_media_cancel_action;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media = global::Sample.Droid.Resource.Layout.notification_template_big_media;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media_custom = global::Sample.Droid.Resource.Layout.notification_template_big_media_custom;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media_narrow = global::Sample.Droid.Resource.Layout.notification_template_big_media_narrow;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_big_media_narrow_custom = global::Sample.Droid.Resource.Layout.notification_template_big_media_narrow_custom;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_custom_big = global::Sample.Droid.Resource.Layout.notification_template_custom_big;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_icon_group = global::Sample.Droid.Resource.Layout.notification_template_icon_group;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_lines_media = global::Sample.Droid.Resource.Layout.notification_template_lines_media;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_media = global::Sample.Droid.Resource.Layout.notification_template_media;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_media_custom = global::Sample.Droid.Resource.Layout.notification_template_media_custom;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_part_chronometer = global::Sample.Droid.Resource.Layout.notification_template_part_chronometer;
			global::SimpleAuth.Google.Droid.Resource.Layout.notification_template_part_time = global::Sample.Droid.Resource.Layout.notification_template_part_time;
			global::SimpleAuth.Google.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_button = global::Sample.Droid.Resource.String.common_google_play_services_enable_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_text = global::Sample.Droid.Resource.String.common_google_play_services_enable_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_title = global::Sample.Droid.Resource.String.common_google_play_services_enable_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_button = global::Sample.Droid.Resource.String.common_google_play_services_install_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_text = global::Sample.Droid.Resource.String.common_google_play_services_install_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_title = global::Sample.Droid.Resource.String.common_google_play_services_install_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_notification_channel_name = global::Sample.Droid.Resource.String.common_google_play_services_notification_channel_name;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_notification_ticker = global::Sample.Droid.Resource.String.common_google_play_services_notification_ticker;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_unknown_issue = global::Sample.Droid.Resource.String.common_google_play_services_unknown_issue;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_unsupported_text = global::Sample.Droid.Resource.String.common_google_play_services_unsupported_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_button = global::Sample.Droid.Resource.String.common_google_play_services_update_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_text = global::Sample.Droid.Resource.String.common_google_play_services_update_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_title = global::Sample.Droid.Resource.String.common_google_play_services_update_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_updating_text = global::Sample.Droid.Resource.String.common_google_play_services_updating_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_wear_update_text = global::Sample.Droid.Resource.String.common_google_play_services_wear_update_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_open_on_phone = global::Sample.Droid.Resource.String.common_open_on_phone;
			global::SimpleAuth.Google.Droid.Resource.String.common_signin_button_text = global::Sample.Droid.Resource.String.common_signin_button_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_signin_button_text_long = global::Sample.Droid.Resource.String.common_signin_button_text_long;
			global::SimpleAuth.Google.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::SimpleAuth.Google.Droid.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::SimpleAuth.Google.Droid.Resource.String.status_bar_notification_info_overflow = global::Sample.Droid.Resource.String.status_bar_notification_info_overflow;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Info = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Time = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Title = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::SimpleAuth.Google.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::Sample.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::SimpleAuth.Google.Droid.Resource.Style.Widget_Compat_NotificationActionContainer = global::Sample.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::SimpleAuth.Google.Droid.Resource.Style.Widget_Compat_NotificationActionText = global::Sample.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::SimpleAuth.Google.Droid.Resource.Style.Widget_Support_CoordinatorLayout = global::Sample.Droid.Resource.Style.Widget_Support_CoordinatorLayout;
			global::SimpleAuth.Google.Droid.Resource.Styleable.ColorStateListItem = global::Sample.Droid.Resource.Styleable.ColorStateListItem;
			global::SimpleAuth.Google.Droid.Resource.Styleable.ColorStateListItem_alpha = global::Sample.Droid.Resource.Styleable.ColorStateListItem_alpha;
			global::SimpleAuth.Google.Droid.Resource.Styleable.ColorStateListItem_android_alpha = global::Sample.Droid.Resource.Styleable.ColorStateListItem_android_alpha;
			global::SimpleAuth.Google.Droid.Resource.Styleable.ColorStateListItem_android_color = global::Sample.Droid.Resource.Styleable.ColorStateListItem_android_color;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout = global::Sample.Droid.Resource.Styleable.CoordinatorLayout;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_keylines = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_keylines;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::SimpleAuth.Google.Droid.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::Sample.Droid.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily = global::Sample.Droid.Resource.Styleable.FontFamily;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont = global::Sample.Droid.Resource.Styleable.FontFamilyFont;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_android_font = global::Sample.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle = global::Sample.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::Sample.Droid.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight = global::Sample.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::Sample.Droid.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_font = global::Sample.Droid.Resource.Styleable.FontFamilyFont_font;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_fontStyle = global::Sample.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::Sample.Droid.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_fontWeight = global::Sample.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamilyFont_ttcIndex = global::Sample.Droid.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderAuthority = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderCerts = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderPackage = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::SimpleAuth.Google.Droid.Resource.Styleable.FontFamily_fontProviderQuery = global::Sample.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor = global::Sample.Droid.Resource.Styleable.GradientColor;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColorItem = global::Sample.Droid.Resource.Styleable.GradientColorItem;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColorItem_android_color = global::Sample.Droid.Resource.Styleable.GradientColorItem_android_color;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColorItem_android_offset = global::Sample.Droid.Resource.Styleable.GradientColorItem_android_offset;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_centerColor = global::Sample.Droid.Resource.Styleable.GradientColor_android_centerColor;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_centerX = global::Sample.Droid.Resource.Styleable.GradientColor_android_centerX;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_centerY = global::Sample.Droid.Resource.Styleable.GradientColor_android_centerY;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_endColor = global::Sample.Droid.Resource.Styleable.GradientColor_android_endColor;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_endX = global::Sample.Droid.Resource.Styleable.GradientColor_android_endX;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_endY = global::Sample.Droid.Resource.Styleable.GradientColor_android_endY;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_gradientRadius = global::Sample.Droid.Resource.Styleable.GradientColor_android_gradientRadius;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_startColor = global::Sample.Droid.Resource.Styleable.GradientColor_android_startColor;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_startX = global::Sample.Droid.Resource.Styleable.GradientColor_android_startX;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_startY = global::Sample.Droid.Resource.Styleable.GradientColor_android_startY;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_tileMode = global::Sample.Droid.Resource.Styleable.GradientColor_android_tileMode;
			global::SimpleAuth.Google.Droid.Resource.Styleable.GradientColor_android_type = global::Sample.Droid.Resource.Styleable.GradientColor_android_type;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView = global::Sample.Droid.Resource.Styleable.LoadingImageView;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_circleCrop = global::Sample.Droid.Resource.Styleable.LoadingImageView_circleCrop;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton = global::Sample.Droid.Resource.Styleable.SignInButton;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_buttonSize = global::Sample.Droid.Resource.Styleable.SignInButton_buttonSize;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_colorScheme = global::Sample.Droid.Resource.Styleable.SignInButton_colorScheme;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_scopeUris = global::Sample.Droid.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int buttonSize = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorScheme = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int coordinatorLayoutStyle = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int font = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderAuthority = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderCerts = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontProviderFetchStrategy = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontProviderFetchTimeout = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontProviderPackage = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontProviderQuery = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int fontStyle = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int fontVariationSettings = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int fontWeight = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int imageAspectRatio = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int imageAspectRatioAdjust = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int keylines = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int layout_anchor = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int layout_anchorGravity = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int layout_behavior = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int layout_dodgeInsetEdges = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int layout_insetEdge = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int layout_keyline = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int scopeUris = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int statusBarBackground = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int ttcIndex = 2130771994;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int common_google_signin_btn_text_dark = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int common_google_signin_btn_text_dark_default = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int common_google_signin_btn_text_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int common_google_signin_btn_text_dark_focused = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int common_google_signin_btn_text_dark_pressed = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int common_google_signin_btn_text_light = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int common_google_signin_btn_text_light_default = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int common_google_signin_btn_text_light_disabled = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int common_google_signin_btn_text_light_focused = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int common_google_signin_btn_text_light_pressed = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int common_google_signin_btn_tint = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int notification_action_color_filter = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int notification_icon_bg_color = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int notification_material_background_media_default_color = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int primary_text_default_material_dark = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int ripple_material_light = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int secondary_text_default_material_dark = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int secondary_text_default_material_light = 2130837521;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int compat_button_inset_horizontal_material = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int compat_button_inset_vertical_material = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_padding_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_padding_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_control_corner_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_notification_large_icon_max_height = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_notification_large_icon_max_width = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int notification_action_icon_size = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int notification_action_text_size = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int notification_big_circle_margin = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int notification_content_margin_start = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_large_icon_height = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_large_icon_width = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_main_column_padding_top = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int notification_media_narrow_margin = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_right_icon_size = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_right_side_padding_top = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_small_icon_background_padding = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_small_icon_size_as_large = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_subtext_size = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_top_pad = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_top_pad_large_text = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int subtitle_corner_radius = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int subtitle_outline_width = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int subtitle_shadow_offset = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int subtitle_shadow_radius = 2130903065;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int common_full_open_on_phone = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int common_google_signin_btn_icon_dark = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int common_google_signin_btn_icon_dark_focused = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int common_google_signin_btn_icon_dark_normal = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int common_google_signin_btn_icon_disabled = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int common_google_signin_btn_icon_light = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int common_google_signin_btn_icon_light_focused = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int common_google_signin_btn_icon_light_normal = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int common_google_signin_btn_icon_light_normal_background = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int common_google_signin_btn_text_dark = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int common_google_signin_btn_text_dark_focused = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int common_google_signin_btn_text_dark_normal = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int common_google_signin_btn_text_dark_normal_background = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int common_google_signin_btn_text_disabled = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int common_google_signin_btn_text_light = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int common_google_signin_btn_text_light_focused = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int common_google_signin_btn_text_light_normal = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int common_google_signin_btn_text_light_normal_background = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int googleg_disabled_color_18 = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int googleg_standard_color_18 = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int Icon = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int notification_action_background = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int notification_bg = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int notification_bg_low = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int notification_bg_low_normal = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int notification_bg_low_pressed = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int notification_bg_normal = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int notification_bg_normal_pressed = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int notification_icon_background = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int notification_template_icon_bg = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int notification_template_icon_low_bg = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int notification_tile_bg = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int notify_panel_notification_icon_bg = 2130968609;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action0 = 2131034112;
			
			// aapt resource value: 0x7F050005
			public const int actions = 2131034117;
			
			// aapt resource value: 0x7F050001
			public const int action_container = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int action_divider = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int action_image = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int action_text = 2131034116;
			
			// aapt resource value: 0x7F050006
			public const int adjust_height = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int adjust_width = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int all = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int async = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int auto = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int blocking = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int bottom = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int cancel_action = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int center = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int center_horizontal = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int center_vertical = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int chronometer = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int clip_horizontal = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int clip_vertical = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int dark = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int end = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int end_padder = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int fill = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int fill_horizontal = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int fill_vertical = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int forever = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int icon = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int icon_group = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int icon_only = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int info = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int italic = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int left = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int light = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int line1 = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int line3 = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int loginButton = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int loginFacebookNative = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int loginGeneric = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int loginGoogleNative = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int media_actions = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int none = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int normal = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int notification_background = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int notification_main_column = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int notification_main_column_container = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int password = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int right = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int right_icon = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int right_side = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int standard = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int start = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int status_bar_latest_event_content = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int tag_transition_group = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int tag_unhandled_key_event_manager = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int tag_unhandled_key_listeners = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int text = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int text2 = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int textView1 = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int time = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int title = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public const int top = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int username = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int wide = 2131034175;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int cancel_button_image_alpha = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int google_play_services_version = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int status_bar_notification_info_maxnum = 2131099650;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int login = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int Main = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int notification_action = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int notification_action_tombstone = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int notification_media_action = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_media_cancel_action = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_template_big_media = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_template_big_media_custom = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_template_big_media_narrow = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_template_big_media_narrow_custom = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_template_custom_big = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int notification_template_icon_group = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int notification_template_lines_media = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int notification_template_media = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int notification_template_media_custom = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int notification_template_part_chronometer = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int notification_template_part_time = 2131165200;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7F080002
			public const int common_google_play_services_enable_button = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int common_google_play_services_enable_text = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int common_google_play_services_enable_title = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int common_google_play_services_install_button = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int common_google_play_services_install_text = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int common_google_play_services_install_title = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int common_google_play_services_notification_channel_name = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int common_google_play_services_notification_ticker = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int common_google_play_services_unknown_issue = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int common_google_play_services_unsupported_text = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int common_google_play_services_update_button = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int common_google_play_services_update_text = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int common_google_play_services_update_title = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int common_google_play_services_updating_text = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int common_google_play_services_wear_update_text = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int common_open_on_phone = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int common_signin_button_text = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int common_signin_button_text_long = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int facebook_app_id = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int fb_login_protocol_scheme = 2131230741;
			
			// aapt resource value: 0x7F080001
			public const int Hello = 2131230721;
			
			// aapt resource value: 0x7F080016
			public const int library_name = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int status_bar_notification_info_overflow = 2131230743;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int TextAppearance_Compat_Notification_Info_Media = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int TextAppearance_Compat_Notification_Line2 = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int TextAppearance_Compat_Notification_Media = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int TextAppearance_Compat_Notification_Time = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int TextAppearance_Compat_Notification_Time_Media = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int TextAppearance_Compat_Notification_Title = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int TextAppearance_Compat_Notification_Title_Media = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int Widget_Compat_NotificationActionContainer = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int Widget_Compat_NotificationActionText = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int Widget_Support_CoordinatorLayout = 2131296268;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010011,0x7F010019 }
			public static int[] CoordinatorLayout = new int[] {
					2130771985,
					2130771993};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F010012,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B }
			public static int[] FontFamily = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010005,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01001A }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771973,
					2130771980,
					2130771981,
					2130771982,
					2130771994};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F010002,0x7F01000F,0x7F010010 }
			public static int[] LoadingImageView = new int[] {
					2130771970,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public const int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F010001,0x7F010003,0x7F010018 }
			public static int[] SignInButton = new int[] {
					2130771969,
					2130771971,
					2130771992};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
