#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SimpleAuth.Resource.Id.loginButton = global::Sample.Droid.Resource.Id.loginButton;
			global::SimpleAuth.Resource.Id.password = global::Sample.Droid.Resource.Id.password;
			global::SimpleAuth.Resource.Id.username = global::Sample.Droid.Resource.Id.username;
			global::SimpleAuth.Resource.Layout.login = global::Sample.Droid.Resource.Layout.login;
			global::SimpleAuth.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.cardBackgroundColor = global::Sample.Droid.Resource.Attribute.cardBackgroundColor;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.cardCornerRadius = global::Sample.Droid.Resource.Attribute.cardCornerRadius;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.cardElevation = global::Sample.Droid.Resource.Attribute.cardElevation;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.cardMaxElevation = global::Sample.Droid.Resource.Attribute.cardMaxElevation;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.cardPreventCornerOverlap = global::Sample.Droid.Resource.Attribute.cardPreventCornerOverlap;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.cardUseCompatPadding = global::Sample.Droid.Resource.Attribute.cardUseCompatPadding;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_auxiliary_view_position = global::Sample.Droid.Resource.Attribute.com_facebook_auxiliary_view_position;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_confirm_logout = global::Sample.Droid.Resource.Attribute.com_facebook_confirm_logout;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_foreground_color = global::Sample.Droid.Resource.Attribute.com_facebook_foreground_color;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_horizontal_alignment = global::Sample.Droid.Resource.Attribute.com_facebook_horizontal_alignment;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_is_cropped = global::Sample.Droid.Resource.Attribute.com_facebook_is_cropped;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_login_text = global::Sample.Droid.Resource.Attribute.com_facebook_login_text;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_logout_text = global::Sample.Droid.Resource.Attribute.com_facebook_logout_text;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_object_id = global::Sample.Droid.Resource.Attribute.com_facebook_object_id;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_object_type = global::Sample.Droid.Resource.Attribute.com_facebook_object_type;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_preset_size = global::Sample.Droid.Resource.Attribute.com_facebook_preset_size;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_style = global::Sample.Droid.Resource.Attribute.com_facebook_style;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.com_facebook_tooltip_mode = global::Sample.Droid.Resource.Attribute.com_facebook_tooltip_mode;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.contentPadding = global::Sample.Droid.Resource.Attribute.contentPadding;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.contentPaddingBottom = global::Sample.Droid.Resource.Attribute.contentPaddingBottom;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.contentPaddingLeft = global::Sample.Droid.Resource.Attribute.contentPaddingLeft;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.contentPaddingRight = global::Sample.Droid.Resource.Attribute.contentPaddingRight;
			global::SimpleAuth.Facebook.Droid.Resource.Attribute.contentPaddingTop = global::Sample.Droid.Resource.Attribute.contentPaddingTop;
			global::SimpleAuth.Facebook.Droid.Resource.Color.cardview_dark_background = global::Sample.Droid.Resource.Color.cardview_dark_background;
			global::SimpleAuth.Facebook.Droid.Resource.Color.cardview_light_background = global::Sample.Droid.Resource.Color.cardview_light_background;
			global::SimpleAuth.Facebook.Droid.Resource.Color.cardview_shadow_end_color = global::Sample.Droid.Resource.Color.cardview_shadow_end_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.cardview_shadow_start_color = global::Sample.Droid.Resource.Color.cardview_shadow_start_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_blue = global::Sample.Droid.Resource.Color.com_facebook_blue;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_background_color = global::Sample.Droid.Resource.Color.com_facebook_button_background_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_background_color_disabled = global::Sample.Droid.Resource.Color.com_facebook_button_background_color_disabled;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_background_color_focused = global::Sample.Droid.Resource.Color.com_facebook_button_background_color_focused;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_background_color_focused_disabled = global::Sample.Droid.Resource.Color.com_facebook_button_background_color_focused_disabled;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_background_color_pressed = global::Sample.Droid.Resource.Color.com_facebook_button_background_color_pressed;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_background_color_selected = global::Sample.Droid.Resource.Color.com_facebook_button_background_color_selected;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_border_color_focused = global::Sample.Droid.Resource.Color.com_facebook_button_border_color_focused;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_login_silver_background_color = global::Sample.Droid.Resource.Color.com_facebook_button_login_silver_background_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_login_silver_background_color_pressed = global::Sample.Droid.Resource.Color.com_facebook_button_login_silver_background_color_pressed;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_send_background_color = global::Sample.Droid.Resource.Color.com_facebook_button_send_background_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_send_background_color_pressed = global::Sample.Droid.Resource.Color.com_facebook_button_send_background_color_pressed;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_button_text_color = global::Sample.Droid.Resource.Color.com_facebook_button_text_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_device_auth_text = global::Sample.Droid.Resource.Color.com_facebook_device_auth_text;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_likeboxcountview_border_color = global::Sample.Droid.Resource.Color.com_facebook_likeboxcountview_border_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_likeboxcountview_text_color = global::Sample.Droid.Resource.Color.com_facebook_likeboxcountview_text_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_likeview_text_color = global::Sample.Droid.Resource.Color.com_facebook_likeview_text_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_messenger_blue = global::Sample.Droid.Resource.Color.com_facebook_messenger_blue;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_send_button_text_color = global::Sample.Droid.Resource.Color.com_facebook_send_button_text_color;
			global::SimpleAuth.Facebook.Droid.Resource.Color.com_facebook_share_button_text_color = global::Sample.Droid.Resource.Color.com_facebook_share_button_text_color;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.cardview_compat_inset_shadow = global::Sample.Droid.Resource.Dimension.cardview_compat_inset_shadow;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.cardview_default_elevation = global::Sample.Droid.Resource.Dimension.cardview_default_elevation;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.cardview_default_radius = global::Sample.Droid.Resource.Dimension.cardview_default_radius;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_auth_dialog_corner_radius = global::Sample.Droid.Resource.Dimension.com_facebook_auth_dialog_corner_radius;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_auth_dialog_corner_radius_oversized = global::Sample.Droid.Resource.Dimension.com_facebook_auth_dialog_corner_radius_oversized;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_button_corner_radius = global::Sample.Droid.Resource.Dimension.com_facebook_button_corner_radius;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeboxcountview_border_radius = global::Sample.Droid.Resource.Dimension.com_facebook_likeboxcountview_border_radius;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeboxcountview_border_width = global::Sample.Droid.Resource.Dimension.com_facebook_likeboxcountview_border_width;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeboxcountview_caret_height = global::Sample.Droid.Resource.Dimension.com_facebook_likeboxcountview_caret_height;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeboxcountview_caret_width = global::Sample.Droid.Resource.Dimension.com_facebook_likeboxcountview_caret_width;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeboxcountview_text_padding = global::Sample.Droid.Resource.Dimension.com_facebook_likeboxcountview_text_padding;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeboxcountview_text_size = global::Sample.Droid.Resource.Dimension.com_facebook_likeboxcountview_text_size;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeview_edge_padding = global::Sample.Droid.Resource.Dimension.com_facebook_likeview_edge_padding;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeview_internal_padding = global::Sample.Droid.Resource.Dimension.com_facebook_likeview_internal_padding;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_likeview_text_size = global::Sample.Droid.Resource.Dimension.com_facebook_likeview_text_size;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_profilepictureview_preset_size_large = global::Sample.Droid.Resource.Dimension.com_facebook_profilepictureview_preset_size_large;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_profilepictureview_preset_size_normal = global::Sample.Droid.Resource.Dimension.com_facebook_profilepictureview_preset_size_normal;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_profilepictureview_preset_size_small = global::Sample.Droid.Resource.Dimension.com_facebook_profilepictureview_preset_size_small;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_share_button_compound_drawable_padding = global::Sample.Droid.Resource.Dimension.com_facebook_share_button_compound_drawable_padding;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_share_button_padding_bottom = global::Sample.Droid.Resource.Dimension.com_facebook_share_button_padding_bottom;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_share_button_padding_left = global::Sample.Droid.Resource.Dimension.com_facebook_share_button_padding_left;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_share_button_padding_right = global::Sample.Droid.Resource.Dimension.com_facebook_share_button_padding_right;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_share_button_padding_top = global::Sample.Droid.Resource.Dimension.com_facebook_share_button_padding_top;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_share_button_text_size = global::Sample.Droid.Resource.Dimension.com_facebook_share_button_text_size;
			global::SimpleAuth.Facebook.Droid.Resource.Dimension.com_facebook_tooltip_horizontal_padding = global::Sample.Droid.Resource.Dimension.com_facebook_tooltip_horizontal_padding;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_auth_dialog_background = global::Sample.Droid.Resource.Drawable.com_facebook_auth_dialog_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_auth_dialog_cancel_background = global::Sample.Droid.Resource.Drawable.com_facebook_auth_dialog_cancel_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_auth_dialog_header_background = global::Sample.Droid.Resource.Drawable.com_facebook_auth_dialog_header_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_background = global::Sample.Droid.Resource.Drawable.com_facebook_button_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_icon = global::Sample.Droid.Resource.Drawable.com_facebook_button_icon;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_icon_blue = global::Sample.Droid.Resource.Drawable.com_facebook_button_icon_blue;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_icon_white = global::Sample.Droid.Resource.Drawable.com_facebook_button_icon_white;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_like_background = global::Sample.Droid.Resource.Drawable.com_facebook_button_like_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_like_icon_selected = global::Sample.Droid.Resource.Drawable.com_facebook_button_like_icon_selected;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_login_silver_background = global::Sample.Droid.Resource.Drawable.com_facebook_button_login_silver_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_send_background = global::Sample.Droid.Resource.Drawable.com_facebook_button_send_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_send_icon_blue = global::Sample.Droid.Resource.Drawable.com_facebook_button_send_icon_blue;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_button_send_icon_white = global::Sample.Droid.Resource.Drawable.com_facebook_button_send_icon_white;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_close = global::Sample.Droid.Resource.Drawable.com_facebook_close;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_favicon_white = global::Sample.Droid.Resource.Drawable.com_facebook_favicon_white;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_profile_picture_blank_portrait = global::Sample.Droid.Resource.Drawable.com_facebook_profile_picture_blank_portrait;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_profile_picture_blank_square = global::Sample.Droid.Resource.Drawable.com_facebook_profile_picture_blank_square;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_send_button_icon = global::Sample.Droid.Resource.Drawable.com_facebook_send_button_icon;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_black_background = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_black_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_black_bottomnub = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_black_bottomnub;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_black_topnub = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_black_topnub;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_black_xout = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_black_xout;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_blue_background = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_blue_background;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_blue_bottomnub = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_blue_bottomnub;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_blue_topnub = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_blue_topnub;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.com_facebook_tooltip_blue_xout = global::Sample.Droid.Resource.Drawable.com_facebook_tooltip_blue_xout;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_bubble_large_blue = global::Sample.Droid.Resource.Drawable.messenger_bubble_large_blue;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_bubble_large_white = global::Sample.Droid.Resource.Drawable.messenger_bubble_large_white;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_bubble_small_blue = global::Sample.Droid.Resource.Drawable.messenger_bubble_small_blue;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_bubble_small_white = global::Sample.Droid.Resource.Drawable.messenger_bubble_small_white;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_button_blue_bg_round = global::Sample.Droid.Resource.Drawable.messenger_button_blue_bg_round;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_button_blue_bg_selector = global::Sample.Droid.Resource.Drawable.messenger_button_blue_bg_selector;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_button_send_round_shadow = global::Sample.Droid.Resource.Drawable.messenger_button_send_round_shadow;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_button_white_bg_round = global::Sample.Droid.Resource.Drawable.messenger_button_white_bg_round;
			global::SimpleAuth.Facebook.Droid.Resource.Drawable.messenger_button_white_bg_selector = global::Sample.Droid.Resource.Drawable.messenger_button_white_bg_selector;
			global::SimpleAuth.Facebook.Droid.Resource.Id.automatic = global::Sample.Droid.Resource.Id.automatic;
			global::SimpleAuth.Facebook.Droid.Resource.Id.bottom = global::Sample.Droid.Resource.Id.bottom;
			global::SimpleAuth.Facebook.Droid.Resource.Id.box_count = global::Sample.Droid.Resource.Id.box_count;
			global::SimpleAuth.Facebook.Droid.Resource.Id.button = global::Sample.Droid.Resource.Id.button;
			global::SimpleAuth.Facebook.Droid.Resource.Id.cancel_button = global::Sample.Droid.Resource.Id.cancel_button;
			global::SimpleAuth.Facebook.Droid.Resource.Id.center = global::Sample.Droid.Resource.Id.center;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_body_frame = global::Sample.Droid.Resource.Id.com_facebook_body_frame;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_button_xout = global::Sample.Droid.Resource.Id.com_facebook_button_xout;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_device_auth_instructions = global::Sample.Droid.Resource.Id.com_facebook_device_auth_instructions;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_device_dialog_title = global::Sample.Droid.Resource.Id.com_facebook_device_dialog_title;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_fragment_container = global::Sample.Droid.Resource.Id.com_facebook_fragment_container;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_login_activity_progress_bar = global::Sample.Droid.Resource.Id.com_facebook_login_activity_progress_bar;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_tooltip_bubble_view_bottom_pointer = global::Sample.Droid.Resource.Id.com_facebook_tooltip_bubble_view_bottom_pointer;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_tooltip_bubble_view_text_body = global::Sample.Droid.Resource.Id.com_facebook_tooltip_bubble_view_text_body;
			global::SimpleAuth.Facebook.Droid.Resource.Id.com_facebook_tooltip_bubble_view_top_pointer = global::Sample.Droid.Resource.Id.com_facebook_tooltip_bubble_view_top_pointer;
			global::SimpleAuth.Facebook.Droid.Resource.Id.confirmation_code = global::Sample.Droid.Resource.Id.confirmation_code;
			global::SimpleAuth.Facebook.Droid.Resource.Id.display_always = global::Sample.Droid.Resource.Id.display_always;
			global::SimpleAuth.Facebook.Droid.Resource.Id.inline = global::Sample.Droid.Resource.Id.inline;
			global::SimpleAuth.Facebook.Droid.Resource.Id.large = global::Sample.Droid.Resource.Id.large;
			global::SimpleAuth.Facebook.Droid.Resource.Id.left = global::Sample.Droid.Resource.Id.left;
			global::SimpleAuth.Facebook.Droid.Resource.Id.loginButton = global::Sample.Droid.Resource.Id.loginButton;
			global::SimpleAuth.Facebook.Droid.Resource.Id.messenger_send_button = global::Sample.Droid.Resource.Id.messenger_send_button;
			global::SimpleAuth.Facebook.Droid.Resource.Id.never_display = global::Sample.Droid.Resource.Id.never_display;
			global::SimpleAuth.Facebook.Droid.Resource.Id.normal = global::Sample.Droid.Resource.Id.normal;
			global::SimpleAuth.Facebook.Droid.Resource.Id.open_graph = global::Sample.Droid.Resource.Id.open_graph;
			global::SimpleAuth.Facebook.Droid.Resource.Id.page = global::Sample.Droid.Resource.Id.page;
			global::SimpleAuth.Facebook.Droid.Resource.Id.password = global::Sample.Droid.Resource.Id.password;
			global::SimpleAuth.Facebook.Droid.Resource.Id.progress_bar = global::Sample.Droid.Resource.Id.progress_bar;
			global::SimpleAuth.Facebook.Droid.Resource.Id.right = global::Sample.Droid.Resource.Id.right;
			global::SimpleAuth.Facebook.Droid.Resource.Id.small = global::Sample.Droid.Resource.Id.small;
			global::SimpleAuth.Facebook.Droid.Resource.Id.standard = global::Sample.Droid.Resource.Id.standard;
			global::SimpleAuth.Facebook.Droid.Resource.Id.top = global::Sample.Droid.Resource.Id.top;
			global::SimpleAuth.Facebook.Droid.Resource.Id.unknown = global::Sample.Droid.Resource.Id.unknown;
			global::SimpleAuth.Facebook.Droid.Resource.Id.username = global::Sample.Droid.Resource.Id.username;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.com_facebook_activity_layout = global::Sample.Droid.Resource.Layout.com_facebook_activity_layout;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.com_facebook_device_auth_dialog_fragment = global::Sample.Droid.Resource.Layout.com_facebook_device_auth_dialog_fragment;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.com_facebook_login_fragment = global::Sample.Droid.Resource.Layout.com_facebook_login_fragment;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.com_facebook_tooltip_bubble = global::Sample.Droid.Resource.Layout.com_facebook_tooltip_bubble;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.login = global::Sample.Droid.Resource.Layout.login;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.messenger_button_send_blue_large = global::Sample.Droid.Resource.Layout.messenger_button_send_blue_large;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.messenger_button_send_blue_round = global::Sample.Droid.Resource.Layout.messenger_button_send_blue_round;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.messenger_button_send_blue_small = global::Sample.Droid.Resource.Layout.messenger_button_send_blue_small;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.messenger_button_send_white_large = global::Sample.Droid.Resource.Layout.messenger_button_send_white_large;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.messenger_button_send_white_round = global::Sample.Droid.Resource.Layout.messenger_button_send_white_round;
			global::SimpleAuth.Facebook.Droid.Resource.Layout.messenger_button_send_white_small = global::Sample.Droid.Resource.Layout.messenger_button_send_white_small;
			global::SimpleAuth.Facebook.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Facebook.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_device_auth_instructions = global::Sample.Droid.Resource.String.com_facebook_device_auth_instructions;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_image_download_unknown_error = global::Sample.Droid.Resource.String.com_facebook_image_download_unknown_error;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_internet_permission_error_message = global::Sample.Droid.Resource.String.com_facebook_internet_permission_error_message;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_internet_permission_error_title = global::Sample.Droid.Resource.String.com_facebook_internet_permission_error_title;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_like_button_liked = global::Sample.Droid.Resource.String.com_facebook_like_button_liked;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_like_button_not_liked = global::Sample.Droid.Resource.String.com_facebook_like_button_not_liked;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loading = global::Sample.Droid.Resource.String.com_facebook_loading;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loginview_cancel_action = global::Sample.Droid.Resource.String.com_facebook_loginview_cancel_action;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loginview_log_in_button = global::Sample.Droid.Resource.String.com_facebook_loginview_log_in_button;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loginview_log_in_button_long = global::Sample.Droid.Resource.String.com_facebook_loginview_log_in_button_long;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loginview_log_out_action = global::Sample.Droid.Resource.String.com_facebook_loginview_log_out_action;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loginview_log_out_button = global::Sample.Droid.Resource.String.com_facebook_loginview_log_out_button;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loginview_logged_in_as = global::Sample.Droid.Resource.String.com_facebook_loginview_logged_in_as;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_loginview_logged_in_using_facebook = global::Sample.Droid.Resource.String.com_facebook_loginview_logged_in_using_facebook;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_send_button_text = global::Sample.Droid.Resource.String.com_facebook_send_button_text;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_share_button_text = global::Sample.Droid.Resource.String.com_facebook_share_button_text;
			global::SimpleAuth.Facebook.Droid.Resource.String.com_facebook_tooltip_default = global::Sample.Droid.Resource.String.com_facebook_tooltip_default;
			global::SimpleAuth.Facebook.Droid.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::SimpleAuth.Facebook.Droid.Resource.String.messenger_send_button_text = global::Sample.Droid.Resource.String.messenger_send_button_text;
			global::SimpleAuth.Facebook.Droid.Resource.Style.Base_CardView = global::Sample.Droid.Resource.Style.Base_CardView;
			global::SimpleAuth.Facebook.Droid.Resource.Style.CardView = global::Sample.Droid.Resource.Style.CardView;
			global::SimpleAuth.Facebook.Droid.Resource.Style.CardView_Dark = global::Sample.Droid.Resource.Style.CardView_Dark;
			global::SimpleAuth.Facebook.Droid.Resource.Style.CardView_Light = global::Sample.Droid.Resource.Style.CardView_Light;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButton = global::Sample.Droid.Resource.Style.MessengerButton;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButton_Blue = global::Sample.Droid.Resource.Style.MessengerButton_Blue;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButton_Blue_Large = global::Sample.Droid.Resource.Style.MessengerButton_Blue_Large;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButton_Blue_Small = global::Sample.Droid.Resource.Style.MessengerButton_Blue_Small;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButton_White = global::Sample.Droid.Resource.Style.MessengerButton_White;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButton_White_Large = global::Sample.Droid.Resource.Style.MessengerButton_White_Large;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButton_White_Small = global::Sample.Droid.Resource.Style.MessengerButton_White_Small;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButtonText = global::Sample.Droid.Resource.Style.MessengerButtonText;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButtonText_Blue = global::Sample.Droid.Resource.Style.MessengerButtonText_Blue;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButtonText_Blue_Large = global::Sample.Droid.Resource.Style.MessengerButtonText_Blue_Large;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButtonText_Blue_Small = global::Sample.Droid.Resource.Style.MessengerButtonText_Blue_Small;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButtonText_White = global::Sample.Droid.Resource.Style.MessengerButtonText_White;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButtonText_White_Large = global::Sample.Droid.Resource.Style.MessengerButtonText_White_Large;
			global::SimpleAuth.Facebook.Droid.Resource.Style.MessengerButtonText_White_Small = global::Sample.Droid.Resource.Style.MessengerButtonText_White_Small;
			global::SimpleAuth.Facebook.Droid.Resource.Style.com_facebook_auth_dialog = global::Sample.Droid.Resource.Style.com_facebook_auth_dialog;
			global::SimpleAuth.Facebook.Droid.Resource.Style.com_facebook_button = global::Sample.Droid.Resource.Style.com_facebook_button;
			global::SimpleAuth.Facebook.Droid.Resource.Style.com_facebook_button_like = global::Sample.Droid.Resource.Style.com_facebook_button_like;
			global::SimpleAuth.Facebook.Droid.Resource.Style.com_facebook_button_send = global::Sample.Droid.Resource.Style.com_facebook_button_send;
			global::SimpleAuth.Facebook.Droid.Resource.Style.com_facebook_button_share = global::Sample.Droid.Resource.Style.com_facebook_button_share;
			global::SimpleAuth.Facebook.Droid.Resource.Style.com_facebook_loginview_default_style = global::Sample.Droid.Resource.Style.com_facebook_loginview_default_style;
			global::SimpleAuth.Facebook.Droid.Resource.Style.com_facebook_loginview_silver_style = global::Sample.Droid.Resource.Style.com_facebook_loginview_silver_style;
			global::SimpleAuth.Facebook.Droid.Resource.Style.tooltip_bubble_text = global::Sample.Droid.Resource.Style.tooltip_bubble_text;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView = global::Sample.Droid.Resource.Styleable.CardView;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_android_minHeight = global::Sample.Droid.Resource.Styleable.CardView_android_minHeight;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_android_minWidth = global::Sample.Droid.Resource.Styleable.CardView_android_minWidth;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_cardBackgroundColor = global::Sample.Droid.Resource.Styleable.CardView_cardBackgroundColor;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_cardCornerRadius = global::Sample.Droid.Resource.Styleable.CardView_cardCornerRadius;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_cardElevation = global::Sample.Droid.Resource.Styleable.CardView_cardElevation;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_cardMaxElevation = global::Sample.Droid.Resource.Styleable.CardView_cardMaxElevation;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_cardPreventCornerOverlap = global::Sample.Droid.Resource.Styleable.CardView_cardPreventCornerOverlap;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_cardUseCompatPadding = global::Sample.Droid.Resource.Styleable.CardView_cardUseCompatPadding;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_contentPadding = global::Sample.Droid.Resource.Styleable.CardView_contentPadding;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_contentPaddingBottom = global::Sample.Droid.Resource.Styleable.CardView_contentPaddingBottom;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_contentPaddingLeft = global::Sample.Droid.Resource.Styleable.CardView_contentPaddingLeft;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_contentPaddingRight = global::Sample.Droid.Resource.Styleable.CardView_contentPaddingRight;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.CardView_contentPaddingTop = global::Sample.Droid.Resource.Styleable.CardView_contentPaddingTop;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_like_view = global::Sample.Droid.Resource.Styleable.com_facebook_like_view;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_auxiliary_view_position = global::Sample.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_auxiliary_view_position;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_foreground_color = global::Sample.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_foreground_color;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_horizontal_alignment = global::Sample.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_horizontal_alignment;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_object_id = global::Sample.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_object_id;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_object_type = global::Sample.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_object_type;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_style = global::Sample.Droid.Resource.Styleable.com_facebook_like_view_com_facebook_style;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_login_view = global::Sample.Droid.Resource.Styleable.com_facebook_login_view;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_confirm_logout = global::Sample.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_confirm_logout;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_login_text = global::Sample.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_login_text;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_logout_text = global::Sample.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_logout_text;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_tooltip_mode = global::Sample.Droid.Resource.Styleable.com_facebook_login_view_com_facebook_tooltip_mode;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_profile_picture_view = global::Sample.Droid.Resource.Styleable.com_facebook_profile_picture_view;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_profile_picture_view_com_facebook_is_cropped = global::Sample.Droid.Resource.Styleable.com_facebook_profile_picture_view_com_facebook_is_cropped;
			global::SimpleAuth.Facebook.Droid.Resource.Styleable.com_facebook_profile_picture_view_com_facebook_preset_size = global::Sample.Droid.Resource.Styleable.com_facebook_profile_picture_view_com_facebook_preset_size;
			global::SimpleAuth.Google.Droid.Resource.Attribute.buttonSize = global::Sample.Droid.Resource.Attribute.buttonSize;
			global::SimpleAuth.Google.Droid.Resource.Attribute.circleCrop = global::Sample.Droid.Resource.Attribute.circleCrop;
			global::SimpleAuth.Google.Droid.Resource.Attribute.colorScheme = global::Sample.Droid.Resource.Attribute.colorScheme;
			global::SimpleAuth.Google.Droid.Resource.Attribute.imageAspectRatio = global::Sample.Droid.Resource.Attribute.imageAspectRatio;
			global::SimpleAuth.Google.Droid.Resource.Attribute.imageAspectRatioAdjust = global::Sample.Droid.Resource.Attribute.imageAspectRatioAdjust;
			global::SimpleAuth.Google.Droid.Resource.Attribute.scopeUris = global::Sample.Droid.Resource.Attribute.scopeUris;
			global::SimpleAuth.Google.Droid.Resource.Color.common_action_bar_splitter = global::Sample.Droid.Resource.Color.common_action_bar_splitter;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_default = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_default = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_disabled = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_focused = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_google_signin_btn_text_light_pressed = global::Sample.Droid.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_dark = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_dark_default = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_dark_disabled = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_dark_pressed = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_light = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_light_default = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_default;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_light_disabled = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_light_focused = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Color.common_plus_signin_btn_text_light_pressed = global::Sample.Droid.Resource.Color.common_plus_signin_btn_text_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_full_open_on_phone = global::Sample.Droid.Resource.Drawable.common_full_open_on_phone;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_pressed = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_icon_light_pressed = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_icon_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_dark_pressed = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_disabled = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_google_signin_btn_text_light_pressed = global::Sample.Droid.Resource.Drawable.common_google_signin_btn_text_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_ic_googleplayservices = global::Sample.Droid.Resource.Drawable.common_ic_googleplayservices;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_focused = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_normal = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_light = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_disabled = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_focused = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_normal = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_pressed = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_icon_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_dark = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_disabled = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_focused = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_normal = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_pressed = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_dark_pressed;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_light = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_light_disabled = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_disabled;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_light_focused = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_focused;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_light_normal = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_normal;
			global::SimpleAuth.Google.Droid.Resource.Drawable.common_plus_signin_btn_text_light_pressed = global::Sample.Droid.Resource.Drawable.common_plus_signin_btn_text_light_pressed;
			global::SimpleAuth.Google.Droid.Resource.Id.adjust_height = global::Sample.Droid.Resource.Id.adjust_height;
			global::SimpleAuth.Google.Droid.Resource.Id.adjust_width = global::Sample.Droid.Resource.Id.adjust_width;
			global::SimpleAuth.Google.Droid.Resource.Id.auto = global::Sample.Droid.Resource.Id.auto;
			global::SimpleAuth.Google.Droid.Resource.Id.dark = global::Sample.Droid.Resource.Id.dark;
			global::SimpleAuth.Google.Droid.Resource.Id.icon_only = global::Sample.Droid.Resource.Id.icon_only;
			global::SimpleAuth.Google.Droid.Resource.Id.light = global::Sample.Droid.Resource.Id.light;
			global::SimpleAuth.Google.Droid.Resource.Id.loginButton = global::Sample.Droid.Resource.Id.loginButton;
			global::SimpleAuth.Google.Droid.Resource.Id.none = global::Sample.Droid.Resource.Id.none;
			global::SimpleAuth.Google.Droid.Resource.Id.password = global::Sample.Droid.Resource.Id.password;
			global::SimpleAuth.Google.Droid.Resource.Id.standard = global::Sample.Droid.Resource.Id.standard;
			global::SimpleAuth.Google.Droid.Resource.Id.username = global::Sample.Droid.Resource.Id.username;
			global::SimpleAuth.Google.Droid.Resource.Id.wide = global::Sample.Droid.Resource.Id.wide;
			global::SimpleAuth.Google.Droid.Resource.Integer.google_play_services_version = global::Sample.Droid.Resource.Integer.google_play_services_version;
			global::SimpleAuth.Google.Droid.Resource.Layout.login = global::Sample.Droid.Resource.Layout.login;
			global::SimpleAuth.Google.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Google.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::SimpleAuth.Google.Droid.Resource.String.auth_google_play_services_client_facebook_display_name = global::Sample.Droid.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::SimpleAuth.Google.Droid.Resource.String.auth_google_play_services_client_google_display_name = global::Sample.Droid.Resource.String.auth_google_play_services_client_google_display_name;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_api_unavailable_text = global::Sample.Droid.Resource.String.common_google_play_services_api_unavailable_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_button = global::Sample.Droid.Resource.String.common_google_play_services_enable_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_text = global::Sample.Droid.Resource.String.common_google_play_services_enable_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_enable_title = global::Sample.Droid.Resource.String.common_google_play_services_enable_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_button = global::Sample.Droid.Resource.String.common_google_play_services_install_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_text_phone = global::Sample.Droid.Resource.String.common_google_play_services_install_text_phone;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_text_tablet = global::Sample.Droid.Resource.String.common_google_play_services_install_text_tablet;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_install_title = global::Sample.Droid.Resource.String.common_google_play_services_install_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_invalid_account_text = global::Sample.Droid.Resource.String.common_google_play_services_invalid_account_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_invalid_account_title = global::Sample.Droid.Resource.String.common_google_play_services_invalid_account_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_network_error_text = global::Sample.Droid.Resource.String.common_google_play_services_network_error_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_network_error_title = global::Sample.Droid.Resource.String.common_google_play_services_network_error_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_notification_ticker = global::Sample.Droid.Resource.String.common_google_play_services_notification_ticker;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_restricted_profile_text = global::Sample.Droid.Resource.String.common_google_play_services_restricted_profile_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_restricted_profile_title = global::Sample.Droid.Resource.String.common_google_play_services_restricted_profile_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_sign_in_failed_text = global::Sample.Droid.Resource.String.common_google_play_services_sign_in_failed_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_sign_in_failed_title = global::Sample.Droid.Resource.String.common_google_play_services_sign_in_failed_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_unknown_issue = global::Sample.Droid.Resource.String.common_google_play_services_unknown_issue;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_unsupported_text = global::Sample.Droid.Resource.String.common_google_play_services_unsupported_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_unsupported_title = global::Sample.Droid.Resource.String.common_google_play_services_unsupported_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_button = global::Sample.Droid.Resource.String.common_google_play_services_update_button;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_text = global::Sample.Droid.Resource.String.common_google_play_services_update_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_update_title = global::Sample.Droid.Resource.String.common_google_play_services_update_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_updating_text = global::Sample.Droid.Resource.String.common_google_play_services_updating_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_updating_title = global::Sample.Droid.Resource.String.common_google_play_services_updating_title;
			global::SimpleAuth.Google.Droid.Resource.String.common_google_play_services_wear_update_text = global::Sample.Droid.Resource.String.common_google_play_services_wear_update_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_open_on_phone = global::Sample.Droid.Resource.String.common_open_on_phone;
			global::SimpleAuth.Google.Droid.Resource.String.common_signin_button_text = global::Sample.Droid.Resource.String.common_signin_button_text;
			global::SimpleAuth.Google.Droid.Resource.String.common_signin_button_text_long = global::Sample.Droid.Resource.String.common_signin_button_text_long;
			global::SimpleAuth.Google.Droid.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView = global::Sample.Droid.Resource.Styleable.LoadingImageView;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_circleCrop = global::Sample.Droid.Resource.Styleable.LoadingImageView_circleCrop;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::SimpleAuth.Google.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton = global::Sample.Droid.Resource.Styleable.SignInButton;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_buttonSize = global::Sample.Droid.Resource.Styleable.SignInButton_buttonSize;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_colorScheme = global::Sample.Droid.Resource.Styleable.SignInButton_colorScheme;
			global::SimpleAuth.Google.Droid.Resource.Styleable.SignInButton_scopeUris = global::Sample.Droid.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int cardBackgroundColor = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardCornerRadius = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cardElevation = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int cardMaxElevation = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int cardPreventCornerOverlap = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int cardUseCompatPadding = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010015
			public const int com_facebook_auxiliary_view_position = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int com_facebook_confirm_logout = 2130771991;
			
			// aapt resource value: 0x7f010011
			public const int com_facebook_foreground_color = 2130771985;
			
			// aapt resource value: 0x7f010016
			public const int com_facebook_horizontal_alignment = 2130771990;
			
			// aapt resource value: 0x7f01001c
			public const int com_facebook_is_cropped = 2130771996;
			
			// aapt resource value: 0x7f010018
			public const int com_facebook_login_text = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int com_facebook_logout_text = 2130771993;
			
			// aapt resource value: 0x7f010012
			public const int com_facebook_object_id = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int com_facebook_object_type = 2130771987;
			
			// aapt resource value: 0x7f01001b
			public const int com_facebook_preset_size = 2130771995;
			
			// aapt resource value: 0x7f010014
			public const int com_facebook_style = 2130771988;
			
			// aapt resource value: 0x7f01001a
			public const int com_facebook_tooltip_mode = 2130771994;
			
			// aapt resource value: 0x7f01000c
			public const int contentPadding = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int contentPaddingBottom = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingLeft = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingRight = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int contentPaddingTop = 2130771983;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060011
			public const int cardview_dark_background = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int cardview_light_background = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int cardview_shadow_end_color = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int cardview_shadow_start_color = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_blue = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_button_background_color = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_button_background_color_disabled = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int com_facebook_button_background_color_focused = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int com_facebook_button_background_color_focused_disabled = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int com_facebook_button_background_color_pressed = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int com_facebook_button_background_color_selected = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int com_facebook_button_border_color_focused = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int com_facebook_button_login_silver_background_color = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int com_facebook_button_login_silver_background_color_pressed = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int com_facebook_button_send_background_color = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int com_facebook_button_send_background_color_pressed = 2131099680;
			
			// aapt resource value: 0x7f060027
			public const int com_facebook_button_text_color = 2131099687;
			
			// aapt resource value: 0x7f060021
			public const int com_facebook_device_auth_text = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int com_facebook_likeboxcountview_border_color = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int com_facebook_likeboxcountview_text_color = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int com_facebook_likeview_text_color = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int com_facebook_messenger_blue = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int com_facebook_send_button_text_color = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int com_facebook_share_button_text_color = 2131099686;
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060029
			public const int common_google_signin_btn_text_dark = 2131099689;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f06002a
			public const int common_google_signin_btn_text_light = 2131099690;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f06002b
			public const int common_plus_signin_btn_text_dark = 2131099691;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f06002c
			public const int common_plus_signin_btn_text_light = 2131099692;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int cardview_compat_inset_shadow = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_default_elevation = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_default_radius = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int com_facebook_auth_dialog_corner_radius = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int com_facebook_auth_dialog_corner_radius_oversized = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int com_facebook_button_corner_radius = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int com_facebook_likeboxcountview_border_radius = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int com_facebook_likeboxcountview_border_width = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int com_facebook_likeboxcountview_caret_height = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int com_facebook_likeboxcountview_caret_width = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int com_facebook_likeboxcountview_text_padding = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int com_facebook_likeboxcountview_text_size = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int com_facebook_likeview_edge_padding = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int com_facebook_likeview_internal_padding = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int com_facebook_likeview_text_size = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int com_facebook_profilepictureview_preset_size_large = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int com_facebook_profilepictureview_preset_size_normal = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int com_facebook_profilepictureview_preset_size_small = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_share_button_compound_drawable_padding = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_share_button_padding_bottom = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int com_facebook_share_button_padding_left = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int com_facebook_share_button_padding_right = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int com_facebook_share_button_padding_top = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int com_facebook_share_button_text_size = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int com_facebook_tooltip_horizontal_padding = 2131230744;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_auth_dialog_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_auth_dialog_cancel_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_auth_dialog_header_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_icon_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_icon_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_like_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_like_icon_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_login_silver_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_send_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_button_send_icon_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_send_icon_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_close = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_favicon_white = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_profile_picture_blank_portrait = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_profile_picture_blank_square = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_send_button_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_tooltip_black_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_tooltip_black_bottomnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_tooltip_black_topnub = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_tooltip_black_xout = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_tooltip_blue_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_tooltip_blue_bottomnub = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_tooltip_blue_topnub = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_tooltip_blue_xout = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_full_open_on_phone = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_icon_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_icon_dark_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_icon_dark_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_icon_dark_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_icon_dark_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_icon_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_google_signin_btn_icon_light_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_google_signin_btn_icon_light_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_google_signin_btn_icon_light_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_google_signin_btn_icon_light_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_google_signin_btn_text_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_google_signin_btn_text_dark_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_google_signin_btn_text_dark_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_google_signin_btn_text_dark_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_google_signin_btn_text_dark_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_google_signin_btn_text_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_google_signin_btn_text_light_disabled = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_google_signin_btn_text_light_focused = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_google_signin_btn_text_light_normal = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_google_signin_btn_text_light_pressed = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_ic_googleplayservices = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_icon_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_plus_signin_btn_icon_dark_focused = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int common_plus_signin_btn_icon_dark_normal = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int common_plus_signin_btn_icon_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int common_plus_signin_btn_icon_light_disabled = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int common_plus_signin_btn_icon_light_focused = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int common_plus_signin_btn_icon_light_normal = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int common_plus_signin_btn_icon_light_pressed = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int common_plus_signin_btn_text_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int common_plus_signin_btn_text_dark_disabled = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int common_plus_signin_btn_text_dark_focused = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int common_plus_signin_btn_text_dark_normal = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int common_plus_signin_btn_text_dark_pressed = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int common_plus_signin_btn_text_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int common_plus_signin_btn_text_light_disabled = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int common_plus_signin_btn_text_light_focused = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int common_plus_signin_btn_text_light_normal = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int common_plus_signin_btn_text_light_pressed = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Icon = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int messenger_bubble_large_blue = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int messenger_bubble_large_white = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int messenger_bubble_small_blue = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int messenger_bubble_small_white = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int messenger_button_blue_bg_round = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int messenger_button_blue_bg_selector = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int messenger_button_send_round_shadow = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int messenger_button_white_bg_round = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int messenger_button_white_bg_selector = 2130837581;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int auto = 2131296262;
			
			// aapt resource value: 0x7f090014
			public const int automatic = 2131296276;
			
			// aapt resource value: 0x7f09000e
			public const int bottom = 2131296270;
			
			// aapt resource value: 0x7f09000c
			public const int box_count = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int button = 2131296269;
			
			// aapt resource value: 0x7f09001f
			public const int cancel_button = 2131296287;
			
			// aapt resource value: 0x7f090011
			public const int center = 2131296273;
			
			// aapt resource value: 0x7f090021
			public const int com_facebook_body_frame = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int com_facebook_button_xout = 2131296291;
			
			// aapt resource value: 0x7f09001c
			public const int com_facebook_device_auth_instructions = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int com_facebook_device_dialog_title = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int com_facebook_fragment_container = 2131296282;
			
			// aapt resource value: 0x7f090020
			public const int com_facebook_login_activity_progress_bar = 2131296288;
			
			// aapt resource value: 0x7f090025
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int com_facebook_tooltip_bubble_view_text_body = 2131296292;
			
			// aapt resource value: 0x7f090022
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131296290;
			
			// aapt resource value: 0x7f09001d
			public const int confirmation_code = 2131296285;
			
			// aapt resource value: 0x7f090007
			public const int dark = 2131296263;
			
			// aapt resource value: 0x7f090015
			public const int display_always = 2131296277;
			
			// aapt resource value: 0x7f090003
			public const int icon_only = 2131296259;
			
			// aapt resource value: 0x7f09000f
			public const int inline = 2131296271;
			
			// aapt resource value: 0x7f090017
			public const int large = 2131296279;
			
			// aapt resource value: 0x7f090012
			public const int left = 2131296274;
			
			// aapt resource value: 0x7f090008
			public const int light = 2131296264;
			
			// aapt resource value: 0x7f090028
			public const int loginButton = 2131296296;
			
			// aapt resource value: 0x7f09002c
			public const int loginFacebookNative = 2131296300;
			
			// aapt resource value: 0x7f09002a
			public const int loginGeneric = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int loginGoogleNative = 2131296299;
			
			// aapt resource value: 0x7f09002d
			public const int messenger_send_button = 2131296301;
			
			// aapt resource value: 0x7f090016
			public const int never_display = 2131296278;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090018
			public const int normal = 2131296280;
			
			// aapt resource value: 0x7f090009
			public const int open_graph = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int page = 2131296266;
			
			// aapt resource value: 0x7f090027
			public const int password = 2131296295;
			
			// aapt resource value: 0x7f09001e
			public const int progress_bar = 2131296286;
			
			// aapt resource value: 0x7f090013
			public const int right = 2131296275;
			
			// aapt resource value: 0x7f090019
			public const int small = 2131296281;
			
			// aapt resource value: 0x7f090004
			public const int standard = 2131296260;
			
			// aapt resource value: 0x7f090029
			public const int textView1 = 2131296297;
			
			// aapt resource value: 0x7f090010
			public const int top = 2131296272;
			
			// aapt resource value: 0x7f09000b
			public const int unknown = 2131296267;
			
			// aapt resource value: 0x7f090026
			public const int username = 2131296294;
			
			// aapt resource value: 0x7f090005
			public const int wide = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_activity_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_device_auth_dialog_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_login_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_tooltip_bubble = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int messenger_button_send_blue_large = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int messenger_button_send_blue_round = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int messenger_button_send_blue_small = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int messenger_button_send_white_large = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int messenger_button_send_white_round = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int messenger_button_send_white_small = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040033
			public const int ApplicationName = 2130968627;
			
			// aapt resource value: 0x7f040032
			public const int Hello = 2130968626;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f04001f
			public const int com_facebook_device_auth_instructions = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int com_facebook_image_download_unknown_error = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int com_facebook_internet_permission_error_message = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int com_facebook_internet_permission_error_title = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int com_facebook_like_button_liked = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int com_facebook_like_button_not_liked = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int com_facebook_loading = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int com_facebook_loginview_cancel_action = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int com_facebook_loginview_log_in_button = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int com_facebook_loginview_log_in_button_long = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int com_facebook_loginview_log_out_action = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int com_facebook_loginview_log_out_button = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int com_facebook_loginview_logged_in_as = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int com_facebook_loginview_logged_in_using_facebook = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int com_facebook_send_button_text = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int com_facebook_share_button_text = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int com_facebook_tooltip_default = 2130968623;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			// aapt resource value: 0x7f040034
			public const int facebook_app_id = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int fb_login_protocol_scheme = 2130968629;
			
			// aapt resource value: 0x7f040031
			public const int library_name = 2130968625;
			
			// aapt resource value: 0x7f040030
			public const int messenger_send_button_text = 2130968624;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Base_CardView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MessengerButton = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int MessengerButton_Blue = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int MessengerButton_Blue_Large = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int MessengerButton_Blue_Small = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int MessengerButton_White = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int MessengerButton_White_Large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int MessengerButton_White_Small = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int MessengerButtonText = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int MessengerButtonText_Blue = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int MessengerButtonText_Blue_Large = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int MessengerButtonText_Blue_Small = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int MessengerButtonText_White = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int MessengerButtonText_White_Large = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int MessengerButtonText_White_Small = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_auth_dialog = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_button = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int com_facebook_button_like = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int com_facebook_button_send = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int com_facebook_button_share = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int com_facebook_loginview_default_style = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int com_facebook_loginview_silver_style = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int tooltip_bubble_text = 2131165209;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771991,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771995,
					2130771996};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
