#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleAuth.Google.Droid.Resource", IsApplication=false)]

namespace SimpleAuth.Google.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public static int font = 2130771981;
			
			// aapt resource value: 0x7f010006
			public static int fontProviderAuthority = 2130771974;
			
			// aapt resource value: 0x7f010009
			public static int fontProviderCerts = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int fontProviderFetchStrategy = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int fontProviderFetchTimeout = 2130771979;
			
			// aapt resource value: 0x7f010007
			public static int fontProviderPackage = 2130771975;
			
			// aapt resource value: 0x7f010008
			public static int fontProviderQuery = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public static int fontStyle = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public static int fontWeight = 2130771982;
			
			// aapt resource value: 0x7f010001
			public static int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public static int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000f
			public static int common_google_signin_btn_text_dark = 2131099663;
			
			// aapt resource value: 0x7f060000
			public static int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060010
			public static int common_google_signin_btn_text_light = 2131099664;
			
			// aapt resource value: 0x7f060004
			public static int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f060011
			public static int common_google_signin_btn_tint = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public static int notification_action_color_filter = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public static int notification_icon_bg_color = 2131099660;
			
			// aapt resource value: 0x7f060008
			public static int notification_material_background_media_default_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int primary_text_default_material_dark = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public static int ripple_material_light = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public static int secondary_text_default_material_dark = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public static int secondary_text_default_material_light = 2131099662;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public static int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public static int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public static int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public static int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public static int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public static int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public static int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public static int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public static int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public static int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public static int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public static int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public static int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public static int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public static int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public static int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public static int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public static int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public static int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public static int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int notification_action_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int notification_bg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int notification_bg_low = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int notification_bg_low_normal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int notification_bg_low_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int notification_bg_normal = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int notification_bg_normal_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int notification_icon_background = 2130837532;
			
			// aapt resource value: 0x7f02001f
			public static int notification_template_icon_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int notification_template_icon_low_bg = 2130837536;
			
			// aapt resource value: 0x7f02001d
			public static int notification_tile_bg = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int notify_panel_notification_icon_bg = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0019
			public static int action0 = 2131361817;
			
			// aapt resource value: 0x7f0a0016
			public static int action_container = 2131361814;
			
			// aapt resource value: 0x7f0a001d
			public static int action_divider = 2131361821;
			
			// aapt resource value: 0x7f0a0017
			public static int action_image = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public static int action_text = 2131361816;
			
			// aapt resource value: 0x7f0a0027
			public static int actions = 2131361831;
			
			// aapt resource value: 0x7f0a0005
			public static int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public static int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000e
			public static int async = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public static int auto = 2131361803;
			
			// aapt resource value: 0x7f0a000f
			public static int blocking = 2131361807;
			
			// aapt resource value: 0x7f0a001a
			public static int cancel_action = 2131361818;
			
			// aapt resource value: 0x7f0a0022
			public static int chronometer = 2131361826;
			
			// aapt resource value: 0x7f0a000c
			public static int dark = 2131361804;
			
			// aapt resource value: 0x7f0a0029
			public static int end_padder = 2131361833;
			
			// aapt resource value: 0x7f0a0010
			public static int forever = 2131361808;
			
			// aapt resource value: 0x7f0a0024
			public static int icon = 2131361828;
			
			// aapt resource value: 0x7f0a0028
			public static int icon_group = 2131361832;
			
			// aapt resource value: 0x7f0a0008
			public static int icon_only = 2131361800;
			
			// aapt resource value: 0x7f0a0023
			public static int info = 2131361827;
			
			// aapt resource value: 0x7f0a0011
			public static int italic = 2131361809;
			
			// aapt resource value: 0x7f0a000d
			public static int light = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public static int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public static int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0015
			public static int loginButton = 2131361813;
			
			// aapt resource value: 0x7f0a001c
			public static int media_actions = 2131361820;
			
			// aapt resource value: 0x7f0a0007
			public static int none = 2131361799;
			
			// aapt resource value: 0x7f0a0012
			public static int normal = 2131361810;
			
			// aapt resource value: 0x7f0a0026
			public static int notification_background = 2131361830;
			
			// aapt resource value: 0x7f0a001f
			public static int notification_main_column = 2131361823;
			
			// aapt resource value: 0x7f0a001e
			public static int notification_main_column_container = 2131361822;
			
			// aapt resource value: 0x7f0a0014
			public static int password = 2131361812;
			
			// aapt resource value: 0x7f0a0025
			public static int right_icon = 2131361829;
			
			// aapt resource value: 0x7f0a0020
			public static int right_side = 2131361824;
			
			// aapt resource value: 0x7f0a0009
			public static int standard = 2131361801;
			
			// aapt resource value: 0x7f0a001b
			public static int status_bar_latest_event_content = 2131361819;
			
			// aapt resource value: 0x7f0a0002
			public static int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public static int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a0021
			public static int time = 2131361825;
			
			// aapt resource value: 0x7f0a0004
			public static int title = 2131361796;
			
			// aapt resource value: 0x7f0a0013
			public static int username = 2131361811;
			
			// aapt resource value: 0x7f0a000a
			public static int wide = 2131361802;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040001
			public static int cancel_button_image_alpha = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int google_play_services_version = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int status_bar_notification_info_maxnum = 2130968578;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int notification_media_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int notification_media_cancel_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int notification_template_big_media = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int notification_template_big_media_custom = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int notification_template_big_media_narrow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int notification_template_big_media_narrow_custom = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int notification_template_custom_big = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int notification_template_icon_group = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int notification_template_lines_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int notification_template_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int notification_template_media_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int notification_template_part_chronometer = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int notification_template_part_time = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050013
			public static int ApplicationName = 2131034131;
			
			// aapt resource value: 0x7f050012
			public static int Hello = 2131034130;
			
			// aapt resource value: 0x7f050001
			public static int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public static int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public static int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public static int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public static int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public static int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public static int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public static int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050014
			public static int library_name = 2131034132;
			
			// aapt resource value: 0x7f050011
			public static int status_bar_notification_info_overflow = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public static int TextAppearance_Compat_Notification = 2131165189;
			
			// aapt resource value: 0x7f070006
			public static int TextAppearance_Compat_Notification_Info = 2131165190;
			
			// aapt resource value: 0x7f070000
			public static int TextAppearance_Compat_Notification_Info_Media = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public static int TextAppearance_Compat_Notification_Line2 = 2131165195;
			
			// aapt resource value: 0x7f070004
			public static int TextAppearance_Compat_Notification_Line2_Media = 2131165188;
			
			// aapt resource value: 0x7f070001
			public static int TextAppearance_Compat_Notification_Media = 2131165185;
			
			// aapt resource value: 0x7f070007
			public static int TextAppearance_Compat_Notification_Time = 2131165191;
			
			// aapt resource value: 0x7f070002
			public static int TextAppearance_Compat_Notification_Time_Media = 2131165186;
			
			// aapt resource value: 0x7f070008
			public static int TextAppearance_Compat_Notification_Title = 2131165192;
			
			// aapt resource value: 0x7f070003
			public static int TextAppearance_Compat_Notification_Title_Media = 2131165187;
			
			// aapt resource value: 0x7f070009
			public static int Widget_Compat_NotificationActionContainer = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public static int Widget_Compat_NotificationActionText = 2131165194;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public static int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public static int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public static int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public static int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
