#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleAuth.Google.Droid.Resource", IsApplication=false)]

namespace SimpleAuth.Google.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.1.99.123")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public static int fragment_fast_out_extra_slow_in = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public static int fragment_close_enter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int fragment_close_exit = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int fragment_fade_enter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int fragment_fade_exit = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int fragment_open_enter = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int fragment_open_exit = 2130837509;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public static int alpha = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int buttonSize = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int circleCrop = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int colorScheme = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int font = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int fontProviderAuthority = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int fontProviderCerts = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int fontProviderFetchStrategy = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int fontProviderFetchTimeout = 2130903048;
			
			// aapt resource value: 0x7F030009
			public static int fontProviderPackage = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public static int fontProviderQuery = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public static int fontStyle = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public static int fontVariationSettings = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public static int fontWeight = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public static int imageAspectRatio = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public static int imageAspectRatioAdjust = 2130903055;
			
			// aapt resource value: 0x7F030010
			public static int scopeUris = 2130903056;
			
			// aapt resource value: 0x7F030011
			public static int ttcIndex = 2130903057;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public static int androidx_core_ripple_material_light = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int androidx_core_secondary_text_default_material_light = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int common_google_signin_btn_text_dark = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int common_google_signin_btn_text_dark_default = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int common_google_signin_btn_text_dark_disabled = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int common_google_signin_btn_text_dark_focused = 2130968581;
			
			// aapt resource value: 0x7F040006
			public static int common_google_signin_btn_text_dark_pressed = 2130968582;
			
			// aapt resource value: 0x7F040007
			public static int common_google_signin_btn_text_light = 2130968583;
			
			// aapt resource value: 0x7F040008
			public static int common_google_signin_btn_text_light_default = 2130968584;
			
			// aapt resource value: 0x7F040009
			public static int common_google_signin_btn_text_light_disabled = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public static int common_google_signin_btn_text_light_focused = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public static int common_google_signin_btn_text_light_pressed = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public static int common_google_signin_btn_tint = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public static int notification_action_color_filter = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public static int notification_icon_bg_color = 2130968590;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public static int compat_button_inset_horizontal_material = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int compat_button_inset_vertical_material = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int compat_button_padding_horizontal_material = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int compat_button_padding_vertical_material = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int compat_control_corner_material = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int compat_notification_large_icon_max_height = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int compat_notification_large_icon_max_width = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int notification_action_icon_size = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int notification_action_text_size = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int notification_big_circle_margin = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int notification_content_margin_start = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int notification_large_icon_height = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int notification_large_icon_width = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int notification_main_column_padding_top = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int notification_media_narrow_margin = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int notification_right_icon_size = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int notification_right_side_padding_top = 2131034128;
			
			// aapt resource value: 0x7F050011
			public static int notification_small_icon_background_padding = 2131034129;
			
			// aapt resource value: 0x7F050012
			public static int notification_small_icon_size_as_large = 2131034130;
			
			// aapt resource value: 0x7F050013
			public static int notification_subtext_size = 2131034131;
			
			// aapt resource value: 0x7F050014
			public static int notification_top_pad = 2131034132;
			
			// aapt resource value: 0x7F050015
			public static int notification_top_pad_large_text = 2131034133;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public static int common_full_open_on_phone = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int common_google_signin_btn_icon_dark = 2131099649;
			
			// aapt resource value: 0x7F060002
			public static int common_google_signin_btn_icon_dark_focused = 2131099650;
			
			// aapt resource value: 0x7F060003
			public static int common_google_signin_btn_icon_dark_normal = 2131099651;
			
			// aapt resource value: 0x7F060004
			public static int common_google_signin_btn_icon_dark_normal_background = 2131099652;
			
			// aapt resource value: 0x7F060005
			public static int common_google_signin_btn_icon_disabled = 2131099653;
			
			// aapt resource value: 0x7F060006
			public static int common_google_signin_btn_icon_light = 2131099654;
			
			// aapt resource value: 0x7F060007
			public static int common_google_signin_btn_icon_light_focused = 2131099655;
			
			// aapt resource value: 0x7F060008
			public static int common_google_signin_btn_icon_light_normal = 2131099656;
			
			// aapt resource value: 0x7F060009
			public static int common_google_signin_btn_icon_light_normal_background = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public static int common_google_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public static int common_google_signin_btn_text_dark_focused = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public static int common_google_signin_btn_text_dark_normal = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public static int common_google_signin_btn_text_dark_normal_background = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public static int common_google_signin_btn_text_disabled = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public static int common_google_signin_btn_text_light = 2131099663;
			
			// aapt resource value: 0x7F060010
			public static int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7F060011
			public static int common_google_signin_btn_text_light_normal = 2131099665;
			
			// aapt resource value: 0x7F060012
			public static int common_google_signin_btn_text_light_normal_background = 2131099666;
			
			// aapt resource value: 0x7F060013
			public static int googleg_disabled_color_18 = 2131099667;
			
			// aapt resource value: 0x7F060014
			public static int googleg_standard_color_18 = 2131099668;
			
			// aapt resource value: 0x7F060015
			public static int notification_action_background = 2131099669;
			
			// aapt resource value: 0x7F060016
			public static int notification_bg = 2131099670;
			
			// aapt resource value: 0x7F060017
			public static int notification_bg_low = 2131099671;
			
			// aapt resource value: 0x7F060018
			public static int notification_bg_low_normal = 2131099672;
			
			// aapt resource value: 0x7F060019
			public static int notification_bg_low_pressed = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public static int notification_bg_normal = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public static int notification_bg_normal_pressed = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public static int notification_icon_background = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public static int notification_template_icon_bg = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public static int notification_template_icon_low_bg = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public static int notification_tile_bg = 2131099679;
			
			// aapt resource value: 0x7F060020
			public static int notify_panel_notification_icon_bg = 2131099680;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070000
			public static int accessibility_action_clickable_span = 2131165184;
			
			// aapt resource value: 0x7F070001
			public static int accessibility_custom_action_0 = 2131165185;
			
			// aapt resource value: 0x7F070002
			public static int accessibility_custom_action_1 = 2131165186;
			
			// aapt resource value: 0x7F070003
			public static int accessibility_custom_action_10 = 2131165187;
			
			// aapt resource value: 0x7F070004
			public static int accessibility_custom_action_11 = 2131165188;
			
			// aapt resource value: 0x7F070005
			public static int accessibility_custom_action_12 = 2131165189;
			
			// aapt resource value: 0x7F070006
			public static int accessibility_custom_action_13 = 2131165190;
			
			// aapt resource value: 0x7F070007
			public static int accessibility_custom_action_14 = 2131165191;
			
			// aapt resource value: 0x7F070008
			public static int accessibility_custom_action_15 = 2131165192;
			
			// aapt resource value: 0x7F070009
			public static int accessibility_custom_action_16 = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public static int accessibility_custom_action_17 = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public static int accessibility_custom_action_18 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public static int accessibility_custom_action_19 = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public static int accessibility_custom_action_2 = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public static int accessibility_custom_action_20 = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public static int accessibility_custom_action_21 = 2131165199;
			
			// aapt resource value: 0x7F070010
			public static int accessibility_custom_action_22 = 2131165200;
			
			// aapt resource value: 0x7F070011
			public static int accessibility_custom_action_23 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public static int accessibility_custom_action_24 = 2131165202;
			
			// aapt resource value: 0x7F070013
			public static int accessibility_custom_action_25 = 2131165203;
			
			// aapt resource value: 0x7F070014
			public static int accessibility_custom_action_26 = 2131165204;
			
			// aapt resource value: 0x7F070015
			public static int accessibility_custom_action_27 = 2131165205;
			
			// aapt resource value: 0x7F070016
			public static int accessibility_custom_action_28 = 2131165206;
			
			// aapt resource value: 0x7F070017
			public static int accessibility_custom_action_29 = 2131165207;
			
			// aapt resource value: 0x7F070018
			public static int accessibility_custom_action_3 = 2131165208;
			
			// aapt resource value: 0x7F070019
			public static int accessibility_custom_action_30 = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public static int accessibility_custom_action_31 = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public static int accessibility_custom_action_4 = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public static int accessibility_custom_action_5 = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public static int accessibility_custom_action_6 = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public static int accessibility_custom_action_7 = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public static int accessibility_custom_action_8 = 2131165215;
			
			// aapt resource value: 0x7F070020
			public static int accessibility_custom_action_9 = 2131165216;
			
			// aapt resource value: 0x7F070025
			public static int actions = 2131165221;
			
			// aapt resource value: 0x7F070021
			public static int action_container = 2131165217;
			
			// aapt resource value: 0x7F070022
			public static int action_divider = 2131165218;
			
			// aapt resource value: 0x7F070023
			public static int action_image = 2131165219;
			
			// aapt resource value: 0x7F070024
			public static int action_text = 2131165220;
			
			// aapt resource value: 0x7F070026
			public static int adjust_height = 2131165222;
			
			// aapt resource value: 0x7F070027
			public static int adjust_width = 2131165223;
			
			// aapt resource value: 0x7F070028
			public static int async = 2131165224;
			
			// aapt resource value: 0x7F070029
			public static int auto = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public static int blocking = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public static int chronometer = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public static int dark = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public static int dialog_button = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public static int forever = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public static int fragment_container_view_tag = 2131165231;
			
			// aapt resource value: 0x7F070030
			public static int icon = 2131165232;
			
			// aapt resource value: 0x7F070031
			public static int icon_group = 2131165233;
			
			// aapt resource value: 0x7F070032
			public static int icon_only = 2131165234;
			
			// aapt resource value: 0x7F070033
			public static int info = 2131165235;
			
			// aapt resource value: 0x7F070034
			public static int italic = 2131165236;
			
			// aapt resource value: 0x7F070035
			public static int light = 2131165237;
			
			// aapt resource value: 0x7F070036
			public static int line1 = 2131165238;
			
			// aapt resource value: 0x7F070037
			public static int line3 = 2131165239;
			
			// aapt resource value: 0x7F070038
			public static int loginButton = 2131165240;
			
			// aapt resource value: 0x7F070039
			public static int none = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public static int normal = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public static int notification_background = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public static int notification_main_column = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public static int notification_main_column_container = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public static int password = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public static int right_icon = 2131165247;
			
			// aapt resource value: 0x7F070040
			public static int right_side = 2131165248;
			
			// aapt resource value: 0x7F070041
			public static int special_effects_controller_view_tag = 2131165249;
			
			// aapt resource value: 0x7F070042
			public static int standard = 2131165250;
			
			// aapt resource value: 0x7F070043
			public static int tag_accessibility_actions = 2131165251;
			
			// aapt resource value: 0x7F070044
			public static int tag_accessibility_clickable_spans = 2131165252;
			
			// aapt resource value: 0x7F070045
			public static int tag_accessibility_heading = 2131165253;
			
			// aapt resource value: 0x7F070046
			public static int tag_accessibility_pane_title = 2131165254;
			
			// aapt resource value: 0x7F070047
			public static int tag_screen_reader_focusable = 2131165255;
			
			// aapt resource value: 0x7F070048
			public static int tag_transition_group = 2131165256;
			
			// aapt resource value: 0x7F070049
			public static int tag_unhandled_key_event_manager = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public static int tag_unhandled_key_listeners = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public static int text = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public static int text2 = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public static int time = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public static int title = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public static int username = 2131165263;
			
			// aapt resource value: 0x7F070050
			public static int view_tree_lifecycle_owner = 2131165264;
			
			// aapt resource value: 0x7F070051
			public static int view_tree_saved_state_registry_owner = 2131165265;
			
			// aapt resource value: 0x7F070052
			public static int view_tree_view_model_store_owner = 2131165266;
			
			// aapt resource value: 0x7F070053
			public static int visible_removing_fragment_view_tag = 2131165267;
			
			// aapt resource value: 0x7F070054
			public static int wide = 2131165268;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public static int google_play_services_version = 2131230720;
			
			// aapt resource value: 0x7F080001
			public static int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090000
			public static int custom_dialog = 2131296256;
			
			// aapt resource value: 0x7F090001
			public static int login = 2131296257;
			
			// aapt resource value: 0x7F090002
			public static int notification_action = 2131296258;
			
			// aapt resource value: 0x7F090003
			public static int notification_action_tombstone = 2131296259;
			
			// aapt resource value: 0x7F090004
			public static int notification_template_custom_big = 2131296260;
			
			// aapt resource value: 0x7F090005
			public static int notification_template_icon_group = 2131296261;
			
			// aapt resource value: 0x7F090006
			public static int notification_template_part_chronometer = 2131296262;
			
			// aapt resource value: 0x7F090007
			public static int notification_template_part_time = 2131296263;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public static int ApplicationName = 2131361792;
			
			// aapt resource value: 0x7F0A0002
			public static int common_google_play_services_enable_button = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public static int common_google_play_services_enable_text = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public static int common_google_play_services_enable_title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public static int common_google_play_services_install_button = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public static int common_google_play_services_install_text = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public static int common_google_play_services_install_title = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public static int common_google_play_services_notification_channel_name = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public static int common_google_play_services_notification_ticker = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public static int common_google_play_services_unknown_issue = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public static int common_google_play_services_unsupported_text = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public static int common_google_play_services_update_button = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public static int common_google_play_services_update_text = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public static int common_google_play_services_update_title = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public static int common_google_play_services_updating_text = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public static int common_google_play_services_wear_update_text = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public static int common_open_on_phone = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public static int common_signin_button_text = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public static int common_signin_button_text_long = 2131361811;
			
			// aapt resource value: 0x7F0A0001
			public static int Hello = 2131361793;
			
			// aapt resource value: 0x7F0A0014
			public static int library_name = 2131361812;
			
			// aapt resource value: 0x7F0A0015
			public static int status_bar_notification_info_overflow = 2131361813;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public static int TextAppearance_Compat_Notification = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public static int TextAppearance_Compat_Notification_Info = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public static int TextAppearance_Compat_Notification_Line2 = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public static int TextAppearance_Compat_Notification_Time = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public static int TextAppearance_Compat_Notification_Title = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public static int Widget_Compat_NotificationActionContainer = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public static int Widget_Compat_NotificationActionText = 2131427334;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F030000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130903040};
			
			// aapt resource value: 2
			public static int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public static int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public static int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F030005,0x7F030006,0x7F030007,0x7F030008,0x7F030009,0x7F03000A }
			public static int[] FontFamily = new int[] {
					2130903045,
					2130903046,
					2130903047,
					2130903048,
					2130903049,
					2130903050};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F030004,0x7F03000B,0x7F03000C,0x7F03000D,0x7F030011 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130903044,
					2130903051,
					2130903052,
					2130903053,
					2130903057};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public static int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public static int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public static int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public static int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public static int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public static int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public static int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x1010003,0x10100D0,0x10100D1 }
			public static int[] Fragment = new int[] {
					16842755,
					16842960,
					16842961};
			
			// aapt resource value: { 0x1010003,0x10100D1 }
			public static int[] FragmentContainerView = new int[] {
					16842755,
					16842961};
			
			// aapt resource value: 0
			public static int FragmentContainerView_android_name = 0;
			
			// aapt resource value: 1
			public static int FragmentContainerView_android_tag = 1;
			
			// aapt resource value: 1
			public static int Fragment_android_id = 1;
			
			// aapt resource value: 0
			public static int Fragment_android_name = 0;
			
			// aapt resource value: 2
			public static int Fragment_android_tag = 2;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public static int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public static int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public static int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public static int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public static int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public static int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public static int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public static int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public static int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public static int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public static int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public static int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public static int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public static int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F030002,0x7F03000E,0x7F03000F }
			public static int[] LoadingImageView = new int[] {
					2130903042,
					2130903054,
					2130903055};
			
			// aapt resource value: 0
			public static int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public static int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F030001,0x7F030003,0x7F030010 }
			public static int[] SignInButton = new int[] {
					2130903041,
					2130903043,
					2130903056};
			
			// aapt resource value: 0
			public static int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public static int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public static int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
