#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleAuth.Facebook.Droid.Resource", IsApplication=false)]

namespace SimpleAuth.Facebook.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f01000f
			public static int com_facebook_auxiliary_view_position = 2130771983;
			
			// aapt resource value: 0x7f010011
			public static int com_facebook_confirm_logout = 2130771985;
			
			// aapt resource value: 0x7f01000b
			public static int com_facebook_foreground_color = 2130771979;
			
			// aapt resource value: 0x7f010010
			public static int com_facebook_horizontal_alignment = 2130771984;
			
			// aapt resource value: 0x7f010016
			public static int com_facebook_is_cropped = 2130771990;
			
			// aapt resource value: 0x7f010012
			public static int com_facebook_login_text = 2130771986;
			
			// aapt resource value: 0x7f010013
			public static int com_facebook_logout_text = 2130771987;
			
			// aapt resource value: 0x7f01000c
			public static int com_facebook_object_id = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public static int com_facebook_object_type = 2130771981;
			
			// aapt resource value: 0x7f010015
			public static int com_facebook_preset_size = 2130771989;
			
			// aapt resource value: 0x7f01000e
			public static int com_facebook_style = 2130771982;
			
			// aapt resource value: 0x7f010014
			public static int com_facebook_tooltip_mode = 2130771988;
			
			// aapt resource value: 0x7f010006
			public static int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public static int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public static int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public static int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public static int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int com_facebook_blue = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int com_facebook_button_background_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int com_facebook_button_background_color_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int com_facebook_button_background_color_focused = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int com_facebook_button_background_color_focused_disabled = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int com_facebook_button_background_color_pressed = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public static int com_facebook_button_background_color_selected = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public static int com_facebook_button_border_color_focused = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public static int com_facebook_button_login_silver_background_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int com_facebook_button_login_silver_background_color_pressed = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int com_facebook_button_send_background_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public static int com_facebook_button_send_background_color_pressed = 2131034127;
			
			// aapt resource value: 0x7f050016
			public static int com_facebook_button_text_color = 2131034134;
			
			// aapt resource value: 0x7f050010
			public static int com_facebook_device_auth_text = 2131034128;
			
			// aapt resource value: 0x7f050011
			public static int com_facebook_likeboxcountview_border_color = 2131034129;
			
			// aapt resource value: 0x7f050012
			public static int com_facebook_likeboxcountview_text_color = 2131034130;
			
			// aapt resource value: 0x7f050013
			public static int com_facebook_likeview_text_color = 2131034131;
			
			// aapt resource value: 0x7f050014
			public static int com_facebook_messenger_blue = 2131034132;
			
			// aapt resource value: 0x7f050017
			public static int com_facebook_send_button_text_color = 2131034135;
			
			// aapt resource value: 0x7f050015
			public static int com_facebook_share_button_text_color = 2131034133;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int cardview_default_radius = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int com_facebook_auth_dialog_corner_radius = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int com_facebook_auth_dialog_corner_radius_oversized = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int com_facebook_button_corner_radius = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int com_facebook_likeboxcountview_border_radius = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int com_facebook_likeboxcountview_border_width = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int com_facebook_likeboxcountview_caret_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int com_facebook_likeboxcountview_caret_width = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int com_facebook_likeboxcountview_text_padding = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public static int com_facebook_likeboxcountview_text_size = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public static int com_facebook_likeview_edge_padding = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public static int com_facebook_likeview_internal_padding = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public static int com_facebook_likeview_text_size = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public static int com_facebook_profilepictureview_preset_size_large = 2131099663;
			
			// aapt resource value: 0x7f060010
			public static int com_facebook_profilepictureview_preset_size_normal = 2131099664;
			
			// aapt resource value: 0x7f060011
			public static int com_facebook_profilepictureview_preset_size_small = 2131099665;
			
			// aapt resource value: 0x7f060012
			public static int com_facebook_share_button_compound_drawable_padding = 2131099666;
			
			// aapt resource value: 0x7f060013
			public static int com_facebook_share_button_padding_bottom = 2131099667;
			
			// aapt resource value: 0x7f060014
			public static int com_facebook_share_button_padding_left = 2131099668;
			
			// aapt resource value: 0x7f060015
			public static int com_facebook_share_button_padding_right = 2131099669;
			
			// aapt resource value: 0x7f060016
			public static int com_facebook_share_button_padding_top = 2131099670;
			
			// aapt resource value: 0x7f060017
			public static int com_facebook_share_button_text_size = 2131099671;
			
			// aapt resource value: 0x7f060018
			public static int com_facebook_tooltip_horizontal_padding = 2131099672;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int com_facebook_auth_dialog_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int com_facebook_auth_dialog_cancel_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int com_facebook_auth_dialog_header_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int com_facebook_button_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int com_facebook_button_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int com_facebook_button_icon_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int com_facebook_button_icon_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int com_facebook_button_like_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int com_facebook_button_like_icon_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int com_facebook_button_login_silver_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int com_facebook_button_send_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int com_facebook_button_send_icon_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int com_facebook_button_send_icon_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int com_facebook_close = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int com_facebook_favicon_white = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int com_facebook_profile_picture_blank_portrait = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int com_facebook_profile_picture_blank_square = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int com_facebook_send_button_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int com_facebook_tooltip_black_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int com_facebook_tooltip_black_bottomnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int com_facebook_tooltip_black_topnub = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int com_facebook_tooltip_black_xout = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int com_facebook_tooltip_blue_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int com_facebook_tooltip_blue_bottomnub = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int com_facebook_tooltip_blue_topnub = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int com_facebook_tooltip_blue_xout = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int messenger_bubble_large_blue = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int messenger_bubble_large_white = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int messenger_bubble_small_blue = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int messenger_bubble_small_white = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int messenger_button_blue_bg_round = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int messenger_button_blue_bg_selector = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int messenger_button_send_round_shadow = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int messenger_button_white_bg_round = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int messenger_button_white_bg_selector = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public static int automatic = 2131230732;
			
			// aapt resource value: 0x7f080006
			public static int bottom = 2131230726;
			
			// aapt resource value: 0x7f080003
			public static int box_count = 2131230723;
			
			// aapt resource value: 0x7f080004
			public static int button = 2131230724;
			
			// aapt resource value: 0x7f080017
			public static int cancel_button = 2131230743;
			
			// aapt resource value: 0x7f080009
			public static int center = 2131230729;
			
			// aapt resource value: 0x7f080019
			public static int com_facebook_body_frame = 2131230745;
			
			// aapt resource value: 0x7f08001b
			public static int com_facebook_button_xout = 2131230747;
			
			// aapt resource value: 0x7f080014
			public static int com_facebook_device_auth_instructions = 2131230740;
			
			// aapt resource value: 0x7f080013
			public static int com_facebook_device_dialog_title = 2131230739;
			
			// aapt resource value: 0x7f080012
			public static int com_facebook_fragment_container = 2131230738;
			
			// aapt resource value: 0x7f080018
			public static int com_facebook_login_activity_progress_bar = 2131230744;
			
			// aapt resource value: 0x7f08001d
			public static int com_facebook_tooltip_bubble_view_bottom_pointer = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public static int com_facebook_tooltip_bubble_view_text_body = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public static int com_facebook_tooltip_bubble_view_top_pointer = 2131230746;
			
			// aapt resource value: 0x7f080015
			public static int confirmation_code = 2131230741;
			
			// aapt resource value: 0x7f08000d
			public static int display_always = 2131230733;
			
			// aapt resource value: 0x7f080007
			public static int inline = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public static int large = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public static int left = 2131230730;
			
			// aapt resource value: 0x7f080020
			public static int loginButton = 2131230752;
			
			// aapt resource value: 0x7f080021
			public static int messenger_send_button = 2131230753;
			
			// aapt resource value: 0x7f08000e
			public static int never_display = 2131230734;
			
			// aapt resource value: 0x7f080010
			public static int normal = 2131230736;
			
			// aapt resource value: 0x7f080000
			public static int open_graph = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int page = 2131230721;
			
			// aapt resource value: 0x7f08001f
			public static int password = 2131230751;
			
			// aapt resource value: 0x7f080016
			public static int progress_bar = 2131230742;
			
			// aapt resource value: 0x7f08000b
			public static int right = 2131230731;
			
			// aapt resource value: 0x7f080011
			public static int small = 2131230737;
			
			// aapt resource value: 0x7f080005
			public static int standard = 2131230725;
			
			// aapt resource value: 0x7f080008
			public static int top = 2131230728;
			
			// aapt resource value: 0x7f080002
			public static int unknown = 2131230722;
			
			// aapt resource value: 0x7f08001e
			public static int username = 2131230750;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int com_facebook_activity_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int com_facebook_device_auth_dialog_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int com_facebook_login_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int com_facebook_tooltip_bubble = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int messenger_button_send_blue_large = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int messenger_button_send_blue_round = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int messenger_button_send_blue_small = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int messenger_button_send_white_large = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int messenger_button_send_white_round = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int messenger_button_send_white_small = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070013
			public static int ApplicationName = 2131165203;
			
			// aapt resource value: 0x7f070012
			public static int Hello = 2131165202;
			
			// aapt resource value: 0x7f070000
			public static int com_facebook_device_auth_instructions = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int com_facebook_image_download_unknown_error = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int com_facebook_internet_permission_error_message = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int com_facebook_internet_permission_error_title = 2131165187;
			
			// aapt resource value: 0x7f070004
			public static int com_facebook_like_button_liked = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int com_facebook_like_button_not_liked = 2131165189;
			
			// aapt resource value: 0x7f070006
			public static int com_facebook_loading = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int com_facebook_loginview_cancel_action = 2131165191;
			
			// aapt resource value: 0x7f070008
			public static int com_facebook_loginview_log_in_button = 2131165192;
			
			// aapt resource value: 0x7f070009
			public static int com_facebook_loginview_log_in_button_long = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public static int com_facebook_loginview_log_out_action = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public static int com_facebook_loginview_log_out_button = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public static int com_facebook_loginview_logged_in_as = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public static int com_facebook_loginview_logged_in_using_facebook = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public static int com_facebook_send_button_text = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public static int com_facebook_share_button_text = 2131165199;
			
			// aapt resource value: 0x7f070010
			public static int com_facebook_tooltip_default = 2131165200;
			
			// aapt resource value: 0x7f070014
			public static int library_name = 2131165204;
			
			// aapt resource value: 0x7f070011
			public static int messenger_send_button_text = 2131165201;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public static int Base_CardView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int CardView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int CardView_Dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int CardView_Light = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int MessengerButton = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int MessengerButton_Blue = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int MessengerButton_Blue_Large = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int MessengerButton_Blue_Small = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int MessengerButton_White = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int MessengerButton_White_Large = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int MessengerButton_White_Small = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int MessengerButtonText = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int MessengerButtonText_Blue = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int MessengerButtonText_Blue_Large = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int MessengerButtonText_Blue_Small = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public static int MessengerButtonText_White = 2130968591;
			
			// aapt resource value: 0x7f040010
			public static int MessengerButtonText_White_Large = 2130968592;
			
			// aapt resource value: 0x7f040011
			public static int MessengerButtonText_White_Small = 2130968593;
			
			// aapt resource value: 0x7f040012
			public static int com_facebook_auth_dialog = 2130968594;
			
			// aapt resource value: 0x7f040013
			public static int com_facebook_button = 2130968595;
			
			// aapt resource value: 0x7f040014
			public static int com_facebook_button_like = 2130968596;
			
			// aapt resource value: 0x7f040015
			public static int com_facebook_button_send = 2130968597;
			
			// aapt resource value: 0x7f040016
			public static int com_facebook_button_share = 2130968598;
			
			// aapt resource value: 0x7f040017
			public static int com_facebook_loginview_default_style = 2130968599;
			
			// aapt resource value: 0x7f040018
			public static int com_facebook_loginview_silver_style = 2130968600;
			
			// aapt resource value: 0x7f040019
			public static int tooltip_bubble_text = 2130968601;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public static int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public static int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public static int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public static int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public static int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public static int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public static int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public static int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public static int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public static int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public static int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public static int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public static int CardView_contentPaddingTop = 11;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 4
			public static int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public static int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public static int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public static int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public static int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public static int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public static int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public static int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public static int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public static int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771989,
					2130771990};
			
			// aapt resource value: 1
			public static int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public static int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
